import type { AnnotatedRhymeChapter } from "./content";

const NO_STORY_TITLE = "这句没有专门故事";

export const RHYME_CHAPTER_THREE = {
  id: "upper-3",
  title: "三江",
  volume: "上卷",
  focus: "从楼阁江海、旗帜钟鼓和古人故事里，发现大小、声音与空间怎样互相照应。",
  sections: [
    {
      title: "第一则 · 楼阁与家国",
      sentences: [
        {
          id: "jiang-1-1",
          text: "楼对阁，户对窗，巨海对长江。",
          pinyin: "lóu duì gé，hù duì chuāng，jù hǎi duì cháng jiāng。",
          meaning: "楼房对楼阁，房门对窗户，辽阔的大海对奔流的长江。",
          terms: [
            { word: "楼", pinyin: "lóu", meaning: "有两层或更多层的建筑。" },
            { word: "阁", pinyin: "gé", meaning: "架高或建在高处、可供远望的建筑。" },
            { word: "巨海", pinyin: "jù hǎi", meaning: "广阔无边的大海。" },
            { word: "长江", pinyin: "cháng jiāng", meaning: "中国最长的河流，向东流入大海。" },
          ],
          pairing: "楼和阁都是建筑，门和窗都是房屋开口；海和江都是大片水域，一个辽阔，一个绵长。",
          storyTitle: NO_STORY_TITLE,
          story: "这句从近处的房屋一路望到远处的江海，像镜头慢慢拉远。",
        },
        {
          id: "jiang-1-2",
          text: "蓉裳对蕙帐，玉斝对银釭。",
          pinyin: "róng cháng duì huì zhàng，yù jiǎ duì yín gāng。",
          meaning: "用荷花想象成的衣裳对带着蕙草香气的帷帐，玉制酒器对银色灯台。",
          terms: [
            { word: "蓉裳", pinyin: "róng cháng", meaning: "像芙蓉花一样美丽的衣裳，也让人想到用荷叶做衣的诗意想象。" },
            { word: "蕙帐", pinyin: "huì zhàng", meaning: "带有蕙草清香的帷帐。蕙是一种香草。" },
            { word: "玉斝", pinyin: "yù jiǎ", meaning: "玉制或像玉一样精美的古代酒器。斝是一种杯。" },
            { word: "银釭", pinyin: "yín gāng", meaning: "银色灯台或灯盏。釭在这里与灯有关。" },
          ],
          pairing: "美丽衣裳对芬芳帷帐，玉杯对银灯；两边都有精美材质、颜色和古代生活器物。",
          storyTitle: "香草与荷衣",
          story: "古人写诗时常用荷花、蕙草代表清香美好的事物。这里是文学想象，不是真的要求用花草做衣服和帐子。",
        },
        {
          id: "jiang-1-3",
          text: "青布幔，碧油幢，宝剑对金缸。",
          pinyin: "qīng bù màn，bì yóu chuáng，bǎo jiàn duì jīn gāng。",
          meaning: "青色布帘对碧色仪仗伞盖，珍贵的剑对金属灯盏。",
          terms: [
            { word: "青布幔", pinyin: "qīng bù màn", meaning: "青色布做成的帘幕。" },
            { word: "碧油幢", pinyin: "bì yóu chuáng", meaning: "古代用涂油碧布制成的伞盖或仪仗。" },
            { word: "宝剑", pinyin: "bǎo jiàn", meaning: "制作精良、受到珍视的剑。" },
            { word: "金缸", pinyin: "jīn gāng", meaning: "金属制的灯盏；这里的缸不是今天装水的大缸。" },
          ],
          pairing: "帘幕对伞盖，宝剑对灯盏；青和碧、宝和金又让器物带上明亮色彩。",
          storyTitle: "同一个字会有旧意思",
          story: "“金缸”在古文里可以指灯盏。读古书时，有些字的意思和今天常用的意思并不一样。",
        },
        {
          id: "jiang-1-4",
          text: "忠心安社稷，利口覆家邦。",
          pinyin: "zhōng xīn ān shè jì，lì kǒu fù jiā bāng。",
          meaning: "忠诚负责的人能帮助国家安定，只会用巧嘴骗人的人可能让国家受害。",
          terms: [
            { word: "忠心", pinyin: "zhōng xīn", meaning: "真诚负责、尽心做事的心。" },
            { word: "利口", pinyin: "lì kǒu", meaning: "嘴上很会说；这里特别指用漂亮话欺骗别人。" },
            { word: "社稷", pinyin: "shè jì", meaning: "古代祭祀土地和谷物的地方，后来常用来代指国家。" },
            { word: "家邦", pinyin: "jiā bāng", meaning: "家国、国家。邦就是国家。" },
          ],
          pairing: "忠心对巧嘴，安定对倾覆，社稷对家邦；两边写诚实担当和欺骗误事带来的不同结果。",
          storyTitle: "行动比漂亮话更重要",
          story: "这句提醒我们判断一个人不能只听他说得多好，还要看他是否诚实、是否真正把事情做好。",
        },
        {
          id: "jiang-1-5",
          text: "世祖中兴延马武，桀王失道杀龙逢。",
          pinyin: "shì zǔ zhōng xīng yán mǎ wǔ，jié wáng shī dào shā lóng páng。",
          meaning: "汉光武帝重新振兴汉朝并重用马武；夏桀不听忠告，杀害了进谏的关龙逢。",
          terms: [
            { word: "世祖", pinyin: "shì zǔ", meaning: "这里指汉光武帝刘秀的庙号。" },
            { word: "桀王", pinyin: "jié wáng", meaning: "传说中夏朝末代君王夏桀。" },
            { word: "马武", pinyin: "mǎ wǔ", meaning: "帮助汉光武帝征战、建立功业的将领。" },
            { word: "龙逢", pinyin: "lóng páng", meaning: "关龙逢，传说中敢于劝谏夏桀的忠臣。" },
          ],
          pairing: "愿意听取人才意见的君王对拒绝忠告的君王，被重用的马武对遭伤害的关龙逢，结果一兴一败。",
          storyTitle: "听得进意见",
          story: "故事把两种做法放在一起：汉光武帝邀请并重用人才，夏桀却伤害劝说自己的人。重点不是记住战争，而是懂得认真听取不同意见。",
        },
        {
          id: "jiang-1-6",
          text: "秋雨潇潇漫烂黄花初满径；春风袅袅扶疏绿竹正盈窗。",
          pinyin: "qiū yǔ xiāo xiāo màn làn huáng huā chū mǎn jìng；chūn fēng niǎo niǎo fú shū lǜ zhú zhèng yíng chuāng。",
          meaning: "绵绵秋雨中，盛开的黄菊铺满小路；轻柔春风里，舒展的绿竹映满窗前。",
          terms: [
            { word: "潇潇", pinyin: "xiāo xiāo", meaning: "这里形容秋雨连绵落下的声音和样子。" },
            { word: "袅袅", pinyin: "niǎo niǎo", meaning: "轻柔、慢慢飘动的样子。" },
            { word: "漫烂", pinyin: "màn làn", meaning: "繁盛鲜明的样子，这里写黄花开得旺盛。" },
            { word: "扶疏", pinyin: "fú shū", meaning: "枝叶茂盛又舒展的样子。" },
          ],
          pairing: "秋雨对春风，黄色菊花对绿色竹子，小径对窗前；一边带着雨声，一边带着轻风。",
          storyTitle: NO_STORY_TITLE,
          story: "这句用叠词把动作放慢：雨“潇潇”地下，风“袅袅”地吹，适合闭上眼睛想象两幅季节画。",
        },
      ],
    },
    {
      title: "第二则 · 山水与钟鼓",
      sentences: [
        {
          id: "jiang-2-1",
          text: "旌对旆，盖对幢，故国对他邦。",
          pinyin: "jīng duì pèi，gài duì chuáng，gù guó duì tā bāng。",
          meaning: "装饰不同的旗子互相对应，伞盖对仪仗帷幢，故乡之国对别的国家。",
          terms: [
            { word: "旌", pinyin: "jīng", meaning: "古代旗杆上带羽毛或彩饰的旗。" },
            { word: "旆", pinyin: "pèi", meaning: "末端像燕尾一样飘动的旗。" },
            { word: "故国", pinyin: "gù guó", meaning: "故乡或从前居住的国家。" },
            { word: "他邦", pinyin: "tā bāng", meaning: "别的国家或地方。" },
          ],
          pairing: "旗对旗，伞盖对帷幢，故乡对他乡；前两组是仪仗器物，后一组是不同地域。",
          storyTitle: "古代队伍里的旗帜",
          story: "古代没有远处可见的电子标牌，队伍常用形状、颜色不同的旗帜表示身份和位置。",
        },
        {
          id: "jiang-2-2",
          text: "千山对万水，九泽对三江。",
          pinyin: "qiān shān duì wàn shuǐ，jiǔ zé duì sān jiāng。",
          meaning: "无数山峰对无数河流，许多湖泽对多条大江。",
          terms: [
            { word: "千山", pinyin: "qiān shān", meaning: "形容山非常多，不一定正好一千座。" },
            { word: "万水", pinyin: "wàn shuǐ", meaning: "形容江河湖溪非常多。" },
            { word: "九泽", pinyin: "jiǔ zé", meaning: "古代对众多湖泊水泽的概括说法。" },
            { word: "三江", pinyin: "sān jiāng", meaning: "古人对几条重要江河的合称，不同古书解释略有不同。" },
          ],
          pairing: "山对水，湖泽对江河；千、万、九、三这些数字共同写出山河众多、天地辽阔。",
          storyTitle: "古文里的数字",
          story: "古文中的“千”“万”常是夸张地说很多。“三江”“九泽”也有不同解释，先感受山河遍布大地的画面即可。",
        },
        {
          id: "jiang-2-3",
          text: "山岌岌，水淙淙，鼓振对钟撞。",
          pinyin: "shān jí jí，shuǐ cóng cóng，gǔ zhèn duì zhōng zhuàng。",
          meaning: "山峰高高耸立，流水发出淙淙声；鼓被敲得震响，对面钟也撞出声音。",
          terms: [
            { word: "岌岌", pinyin: "jí jí", meaning: "山势高耸的样子。" },
            { word: "淙淙", pinyin: "cóng cóng", meaning: "流水发出的轻快声音。" },
            { word: "鼓振", pinyin: "gǔ zhèn", meaning: "鼓面受到敲击，发出震动的声音。" },
            { word: "钟撞", pinyin: "zhōng zhuàng", meaning: "钟被撞击后发出悠长声音。" },
          ],
          pairing: "高山对流水，鼓声对钟声；前面一静一动，后面都是可以传到远处的响声。",
          storyTitle: NO_STORY_TITLE,
          story: "“淙淙”像流水在说话，“振”和“撞”又让钟鼓响起来，读这句时可以想象由轻到响的声音。",
        },
        {
          id: "jiang-2-4",
          text: "清风生酒舍，皓月照书窗。",
          pinyin: "qīng fēng shēng jiǔ shè，hào yuè zhào shū chuāng。",
          meaning: "清风吹过古代客店，明亮月光照着读书人的窗户。",
          terms: [
            { word: "清风", pinyin: "qīng fēng", meaning: "清凉、轻柔的风。" },
            { word: "皓月", pinyin: "hào yuè", meaning: "洁白明亮的月亮。皓就是明亮洁白。" },
            { word: "酒舍", pinyin: "jiǔ shè", meaning: "古代供人吃饭休息的店铺；儿童只理解历史场景，不能饮酒。" },
            { word: "书窗", pinyin: "shū chuāng", meaning: "书房的窗户，也让人想到窗前读书。" },
          ],
          pairing: "清风对明月，旅店对书房，风吹对月照；一个场景有人来往，一个场景安静读书。",
          storyTitle: NO_STORY_TITLE,
          story: "这句把夜晚分成两处：外面的客店有清风，里面的书房有月光，气氛都很安静。",
        },
        {
          id: "jiang-2-5",
          text: "阵上倒戈辛纣战，道旁系剑子婴降。",
          pinyin: "zhèn shàng dǎo gē xīn zhòu zhàn，dào páng xì jiàn zǐ yīng xiáng。",
          meaning: "商纣王作战时，军队临阵倒戈；秦王子婴投降时，在路旁系着佩剑表示放下武器。",
          terms: [
            { word: "倒戈", pinyin: "dǎo gē", meaning: "把兵器转向原来的队伍，表示不再为它作战。" },
            { word: "系剑", pinyin: "xì jiàn", meaning: "把佩剑系住或放下，故事中表示停止抵抗。" },
            { word: "辛纣", pinyin: "xīn zhòu", meaning: "商朝末代君王帝辛，也常称商纣王。" },
            { word: "子婴", pinyin: "zǐ yīng", meaning: "秦朝最后一位统治者，后来向刘邦投降。" },
          ],
          pairing: "战场对路旁，倒戈对系剑，商朝末代君王对秦朝末代统治者；两边都写王朝结束时停止作战。",
          storyTitle: "放下武器的历史场景",
          story: "这些故事记录古代战争和王朝更替，不是鼓励打斗。我们重点理解：失去人心会让队伍离开，停止抵抗有时也能减少伤害。",
        },
        {
          id: "jiang-2-6",
          text: "夏日池塘出没浴波鸥对对；春风帘幕往来营垒燕双双。",
          pinyin: "xià rì chí táng chū mò yù bō ōu duì duì；chūn fēng lián mù wǎng lái yíng lěi yàn shuāng shuāng。",
          meaning: "夏日池塘里，成对水鸥在波上浮沉洗浴；春风帘幕间，成双燕子来回衔泥筑巢。",
          terms: [
            { word: "鸥对对", pinyin: "ōu duì duì", meaning: "水鸥一对一对地活动。" },
            { word: "燕双双", pinyin: "yàn shuāng shuāng", meaning: "燕子成双飞来飞去。" },
            { word: "浴波", pinyin: "yù bō", meaning: "在水波中洗浴、浮游。" },
            { word: "营垒", pinyin: "yíng lěi", meaning: "原指修筑营地，这里借来形容燕子营造鸟巢。" },
          ],
          pairing: "夏日对春风，池塘对帘幕，水鸥对燕子；一边在水波出没，一边在屋檐往来筑巢。",
          storyTitle: NO_STORY_TITLE,
          story: "“对对”和“双双”都在说两个伙伴一起活动，让池塘和屋檐两幅画显得热闹又温柔。",
        },
      ],
    },
    {
      title: "第三则 · 度量与古人",
      sentences: [
        {
          id: "jiang-3-1",
          text: "铢对两，只对双，华岳对湘江。",
          pinyin: "zhū duì liǎng，zhī duì shuāng，huà yuè duì xiāng jiāng。",
          meaning: "很小的重量单位铢对较大的两，单个对成双；华山对湘江。",
          terms: [
            { word: "铢", pinyin: "zhū", meaning: "古代很小的重量单位。" },
            { word: "两", pinyin: "liǎng", meaning: "古代重量单位，比铢大。" },
            { word: "华岳", pinyin: "huà yuè", meaning: "华山，五岳中的西岳。这里“华”读四声。" },
            { word: "湘江", pinyin: "xiāng jiāng", meaning: "流经湖南的重要河流。" },
          ],
          pairing: "小重量对大重量，一个对两个，高山对大江；从数字大小写到山水形态。",
          storyTitle: "古代怎样称重量",
          story: "古人的铢、两像今天的克和千克一样用来称重量，但换算方法不完全相同，这里只需知道铢小、两大。",
        },
        {
          id: "jiang-3-2",
          text: "朝车对禁鼓，宿火对寒缸。",
          pinyin: "cháo chē duì jìn gǔ，sù huǒ duì hán gāng。",
          meaning: "上朝的车马对宫中报时的鼓，夜里留存的火种对寒夜里的灯盏。",
          terms: [
            { word: "朝车", pinyin: "cháo chē", meaning: "古代官员上朝时乘坐的车。" },
            { word: "禁鼓", pinyin: "jìn gǔ", meaning: "宫城中报时、传令的鼓。禁在这里指皇宫。" },
            { word: "宿火", pinyin: "sù huǒ", meaning: "从夜里保存到清晨的火种。" },
            { word: "寒缸", pinyin: "hán gāng", meaning: "寒夜里的灯盏，缸在这里指灯。" },
          ],
          pairing: "上朝车马对宫中鼓声，火种对灯光；两边都带着古人清晨或夜晚生活的时间感。",
          storyTitle: "没有电灯的夜晚",
          story: "古人会小心保存火种，也用油灯照明。这里的“缸”是旧时灯具称呼，不是装水的大缸。",
        },
        {
          id: "jiang-3-3",
          text: "青琐闼，碧纱窗，汉社对周邦。",
          pinyin: "qīng suǒ tà，bì shā chuāng，hàn shè duì zhōu bāng。",
          meaning: "带青色纹饰的宫门对蒙着碧纱的窗，汉代国家对周代国家。",
          terms: [
            { word: "青琐闼", pinyin: "qīng suǒ tà", meaning: "带青色连环纹饰的宫门。闼就是门。" },
            { word: "碧纱窗", pinyin: "bì shā chuāng", meaning: "蒙着青绿色薄纱的窗户。" },
            { word: "汉社", pinyin: "hàn shè", meaning: "汉代国家；社原指土地祭坛。" },
            { word: "周邦", pinyin: "zhōu bāng", meaning: "周代国家。邦就是国家。" },
          ],
          pairing: "宫门对纱窗，汉对周，社对邦；前一组是精美建筑细节，后一组是两个朝代。",
          storyTitle: NO_STORY_TITLE,
          story: "青色宫门和碧色纱窗让古代建筑有了颜色，“汉社”“周邦”则把视线推到更长的历史中。",
        },
        {
          id: "jiang-3-4",
          text: "笙箫鸣细细，钟鼓响摐摐。",
          pinyin: "shēng xiāo míng xì xì，zhōng gǔ xiǎng chuāng chuāng。",
          meaning: "笙和箫吹出细柔声音，钟和鼓发出洪亮撞击声。",
          terms: [
            { word: "笙箫", pinyin: "shēng xiāo", meaning: "两类古代吹奏乐器，声音较轻柔悠长。" },
            { word: "钟鼓", pinyin: "zhōng gǔ", meaning: "钟和鼓，敲击后声音响亮。" },
            { word: "细细", pinyin: "xì xì", meaning: "声音轻细柔和的样子。" },
            { word: "摐摐", pinyin: "chuāng chuāng", meaning: "形容钟鼓撞击时洪亮连续的声音。" },
          ],
          pairing: "吹奏乐器对敲击乐器，细柔声对洪亮声；两边都在写音乐，却有不同音量和质感。",
          storyTitle: "一轻一响的乐队",
          story: "可以把笙箫想成轻轻唱歌，把钟鼓想成有力打拍子。不同声音合在一起，音乐才会有层次。",
        },
        {
          id: "jiang-3-5",
          text: "主簿栖鸾名有览，治中展骥姓惟庞。",
          pinyin: "zhǔ bù qī luán míng yǒu lǎn，zhì zhōng zhǎn jì xìng wéi páng。",
          meaning: "仇览做主簿也像鸾鸟栖息般有才德；庞统担任治中后，才像骏马一样施展本领。",
          terms: [
            { word: "栖鸾", pinyin: "qī luán", meaning: "让鸾鸟栖息，比喻有才德的人在职位上做事。" },
            { word: "展骥", pinyin: "zhǎn jì", meaning: "让骏马伸展脚力，比喻人才得到发挥。" },
            { word: "主簿", pinyin: "zhǔ bù", meaning: "古代管理文书等事务的官职。" },
            { word: "治中", pinyin: "zhì zhōng", meaning: "古代协助地方长官处理事务的官职。" },
          ],
          pairing: "仇览对庞统，主簿对治中，鸾鸟对骏马；两边都用珍贵动物比喻有才能的人。",
          storyTitle: "让人才找到合适位置",
          story: "故事说仇览官职虽小仍认真做事，庞统则需要更适合的职位才能施展才能。每个人擅长的事情不同，找到合适位置很重要。",
        },
        {
          id: "jiang-3-6",
          text: "苏武牧羊雪屡餐于北海；庄周活鲋水必决于西江。",
          pinyin: "sū wǔ mù yáng xuě lǚ cān yú běi hǎi；zhuāng zhōu huó fù shuǐ bì jué yú xī jiāng。",
          meaning: "苏武在北海牧羊，缺少食物时甚至以雪充饥；庄子遇见缺水的鲫鱼，却说要引西江之水来救。",
          terms: [
            { word: "苏武", pinyin: "sū wǔ", meaning: "汉代使者，被扣留多年仍坚持自己的责任。" },
            { word: "庄周", pinyin: "zhuāng zhōu", meaning: "战国时期思想家庄子，许多寓言与他有关。" },
            { word: "北海", pinyin: "běi hǎi", meaning: "故事中苏武牧羊的寒冷远方。" },
            { word: "西江", pinyin: "xī jiāng", meaning: "寓言里庄子说要引来的遥远大江之水。" },
          ],
          pairing: "真实历史人物对寓言人物，北海对西江，缺食对缺水；一个写困境中的坚持，一个写远水救不了近鱼。",
          storyTitle: "坚持与及时帮助",
          story: "苏武故事赞美在困难中守住责任。庄周和鲋鱼的寓言提醒我们：别人现在只需要一点水，就不要只许诺将来很大的帮助，及时行动更有用。",
        },
      ],
    },
  ],
} as const satisfies AnnotatedRhymeChapter;
