import type { AnnotatedRhymeChapter } from "./content";

const NO_STORY_TITLE = "这句没有专门故事";

export const RHYME_CHAPTER_FIVE = {
  id: "upper-5",
  title: "五微",
  volume: "上卷",
  focus: "从朝露晚霞、花木归途和古代人物中，感受疏密、来往、明暗与远近的变化。",
  sections: [
    {
      title: "第一则 · 朝露与归途",
      sentences: [
        {
          id: "wei-1-1",
          text: "来对往，密对稀，燕舞对莺飞。",
          pinyin: "lái duì wǎng，mì duì xī，yàn wǔ duì yīng fēi。",
          meaning: "来到对离去，密集对稀疏，燕子轻舞对黄莺飞翔。",
          terms: [
            { word: "来", pinyin: "lái", meaning: "向着说话人的方向靠近。" },
            { word: "往", pinyin: "wǎng", meaning: "离开这里，向别处去。" },
            { word: "密", pinyin: "mì", meaning: "数量多、彼此靠得近。" },
            { word: "稀", pinyin: "xī", meaning: "数量少、彼此距离较远。" },
          ],
          pairing: "来和往、密和稀都是相反变化；燕子和黄莺都是鸟，舞和飞都写它们在空中的动作。",
          storyTitle: NO_STORY_TITLE,
          story: "可以用身体感受这句：向前一步是来，向后一步是往；站得近是密，分开些是稀。",
        },
        {
          id: "wei-1-2",
          text: "风清对月朗，露重对烟微。",
          pinyin: "fēng qīng duì yuè lǎng，lù zhòng duì yān wēi。",
          meaning: "风儿清爽对月光明朗，露水浓重对薄雾轻微。",
          terms: [
            { word: "风清", pinyin: "fēng qīng", meaning: "风吹来清爽、洁净。" },
            { word: "月朗", pinyin: "yuè lǎng", meaning: "月亮明亮，月光清晰。" },
            { word: "露重", pinyin: "lù zhòng", meaning: "露水很多，沾在草木上显得湿重。" },
            { word: "烟微", pinyin: "yān wēi", meaning: "雾气或炊烟很淡、若有若无。" },
          ],
          pairing: "清风对朗月，浓露对淡烟；前一组清透明亮，后一组用重和微比较浓淡。",
          storyTitle: NO_STORY_TITLE,
          story: "“重”不是说一滴露水真的很重，而是说露水浓、沾得多；“微”则让薄雾像快要看不见。",
        },
        {
          id: "wei-1-3",
          text: "霜菊瘦，雨梅肥，客路对鱼矶。",
          pinyin: "shuāng jú shòu，yǔ méi féi，kè lù duì yú jī。",
          meaning: "经霜的菊花显得清瘦，经雨的梅子显得饱满；旅人行走的路对渔人停留的水边石滩。",
          terms: [
            { word: "霜菊瘦", pinyin: "shuāng jú shòu", meaning: "菊花经霜后枝叶清瘦，却仍能开放。" },
            { word: "雨梅肥", pinyin: "yǔ méi féi", meaning: "梅子得到雨水滋润，果实饱满。" },
            { word: "客路", pinyin: "kè lù", meaning: "旅人在外行走的道路。" },
            { word: "鱼矶", pinyin: "yú jī", meaning: "水边可供垂钓、停船的石滩或石台。" },
          ],
          pairing: "菊花对梅子，瘦对肥，旅途道路对水边钓台；一组写植物样子，一组写人在不同地方活动。",
          storyTitle: NO_STORY_TITLE,
          story: "这里用人的“瘦”和“肥”形容植物，是拟人写法。不是评价外形好坏，而是在比较经霜和经雨后的样子。",
        },
        {
          id: "wei-1-4",
          text: "晚霞舒锦绣，朝露缀珠玑。",
          pinyin: "wǎn xiá shū jǐn xiù，zhāo lù zhuì zhū jī。",
          meaning: "晚霞铺展得像彩色锦绣，清晨露珠点缀草木，像一颗颗珍珠。",
          terms: [
            { word: "晚霞", pinyin: "wǎn xiá", meaning: "傍晚被阳光染出颜色的云。" },
            { word: "朝露", pinyin: "zhāo lù", meaning: "清晨凝结在草木上的小水珠。" },
            { word: "锦绣", pinyin: "jǐn xiù", meaning: "色彩美丽、花纹精致的丝织品。" },
            { word: "珠玑", pinyin: "zhū jī", meaning: "圆珠和小珠，这里比喻晶亮露珠。" },
          ],
          pairing: "傍晚对清晨，天上彩霞对草上露珠，铺展的锦绣对点缀的珍珠；一大片对一颗颗。",
          storyTitle: NO_STORY_TITLE,
          story: "霞并不是布，露也不是珠宝。比喻把天空和草木变成了一个色彩明亮的展览馆。",
        },
        {
          id: "wei-1-5",
          text: "夏暑客思欹石枕，秋寒妇念寄边衣。",
          pinyin: "xià shǔ kè sī qī shí zhěn，qiū hán fù niàn jì biān yī。",
          meaning: "夏日炎热，旅人想斜靠清凉石枕休息；秋天转寒，家中女子惦记远方亲人，想寄去御寒衣物。",
          terms: [
            { word: "夏暑", pinyin: "xià shǔ", meaning: "夏天炎热的天气。" },
            { word: "秋寒", pinyin: "qiū hán", meaning: "秋天渐渐出现的寒意。" },
            { word: "欹石枕", pinyin: "qī shí zhěn", meaning: "斜靠石制或像石一样清凉的枕头。欹是斜靠。" },
            { word: "寄边衣", pinyin: "jì biān yī", meaning: "给远在边地的人寄送御寒衣服。" },
          ],
          pairing: "夏天对秋天，暑热对寒冷，旅人想休息对家人寄寒衣；两边都写天气带来的牵挂。",
          storyTitle: "古代远行与寄衣",
          story: "古代交通和通信很慢，远行的人可能很久不能回家。“寄边衣”写的是家人彼此惦念，并不是说照顾家庭只能由女子承担。",
        },
        {
          id: "wei-1-6",
          text: "春水才深清草岸边渔父去；夕阳半落绿莎原上牧童归。",
          pinyin: "chūn shuǐ cái shēn qīng cǎo àn biān yú fǔ qù；xī yáng bàn luò lǜ suō yuán shàng mù tóng guī。",
          meaning: "春水刚刚涨深，渔父从青草岸边离去；夕阳落下一半，牧童从绿草原野上归来。",
          terms: [
            { word: "渔父去", pinyin: "yú fǔ qù", meaning: "捕鱼人从水岸离开。父在这里是对成年男子的旧称。" },
            { word: "牧童归", pinyin: "mù tóng guī", meaning: "放牧的孩子赶着牲畜回家。" },
            { word: "青草岸", pinyin: "qīng cǎo àn", meaning: "长着青嫩草木的水岸。" },
            { word: "绿莎原", pinyin: "lǜ suō yuán", meaning: "长满莎草的绿色原野。" },
          ],
          pairing: "春水对夕阳，岸边对原上，渔父离去对牧童归来；一个靠水，一个在草原。",
          storyTitle: "两个方向的傍晚画面",
          story: "渔父“去”、牧童“归”，方向不同，却都在一天劳作后移动。读到最后，好像看见夕阳把两条路连在一起。",
        },
      ],
    },
    {
      title: "第二则 · 花木与兴替",
      sentences: [
        {
          id: "wei-2-1",
          text: "宽对猛，是对非，服美对乘肥。",
          pinyin: "kuān duì měng，shì duì fēi，fú měi duì chéng féi。",
          meaning: "宽和的办法对严厉的办法，正确对错误；穿着华美衣服对乘坐肥壮好马。",
          terms: [
            { word: "宽", pinyin: "kuān", meaning: "这里指待人或处理事情较宽和。" },
            { word: "猛", pinyin: "měng", meaning: "这里指做法严厉、力度很强。" },
            { word: "服美", pinyin: "fú měi", meaning: "穿着漂亮精美的衣服。" },
            { word: "乘肥", pinyin: "chéng féi", meaning: "乘坐由肥壮好马拉的车，古时形容生活优裕。" },
          ],
          pairing: "宽和对严厉，正确对错误，漂亮衣服对肥壮马匹；前两组讲判断和做法，后一组讲古代富足生活。",
          storyTitle: "宽和与严格都要合适",
          story: "处理事情不能永远宽松，也不能总是严厉。更重要的是了解情况、保护别人，再选择合适办法。",
        },
        {
          id: "wei-2-2",
          text: "珊瑚对玳瑁，锦绣对珠玑。",
          pinyin: "shān hú duì dài mào，jǐn xiù duì zhū jī。",
          meaning: "海中珊瑚对玳瑁，华美丝织品对珍珠。",
          terms: [
            { word: "珊瑚", pinyin: "shān hú", meaning: "珊瑚虫形成的海洋生物群体，是重要海洋生态家园。" },
            { word: "玳瑁", pinyin: "dài mào", meaning: "生活在热带海洋的海龟，是需要保护的野生动物。" },
            { word: "锦绣", pinyin: "jǐn xiù", meaning: "有美丽花纹的丝织品。" },
            { word: "珠玑", pinyin: "zhū jī", meaning: "大小不同的珍珠，也用来形容珍贵美好。" },
          ],
          pairing: "珊瑚对玳瑁，都是海中珍贵事物；锦绣对珍珠，都是古人眼中华美的物品。",
          storyTitle: "今天要保护海洋生命",
          story: "古人曾把珊瑚和玳瑁当珍宝。今天我们知道玳瑁受到威胁，不购买野生动物制品，才是真正珍惜海洋。",
        },
        {
          id: "wei-2-3",
          text: "桃灼灼，柳依依，绿暗对红稀。",
          pinyin: "táo zhuó zhuó，liǔ yī yī，lǜ àn duì hóng xī。",
          meaning: "桃花鲜艳明亮，柳条柔软轻垂；绿叶渐浓对红花渐少。",
          terms: [
            { word: "桃灼灼", pinyin: "táo zhuó zhuó", meaning: "桃花鲜明盛开的样子，让人想到《诗经》“灼灼其华”。" },
            { word: "柳依依", pinyin: "liǔ yī yī", meaning: "柳条柔软、轻轻随风摆动的样子。" },
            { word: "绿暗", pinyin: "lǜ àn", meaning: "绿叶长得浓密，颜色显得深。" },
            { word: "红稀", pinyin: "hóng xī", meaning: "红花渐渐凋落，数量变少。" },
          ],
          pairing: "桃花对柳条，鲜明对柔软，浓绿对稀红；植物从花多叶嫩慢慢变成叶密花少。",
          storyTitle: "季节会改变颜色多少",
          story: "春天刚来时花很醒目，后来叶子越长越密、花渐渐落下。“绿暗红稀”把季节变化浓缩成四个字。",
        },
        {
          id: "wei-2-4",
          text: "窗前莺并语，帘外燕双飞。",
          pinyin: "chuāng qián yīng bìng yǔ，lián wài yàn shuāng fēi。",
          meaning: "窗前两只黄莺像在一同说话，帘外一双燕子并肩飞翔。",
          terms: [
            { word: "莺并语", pinyin: "yīng bìng yǔ", meaning: "黄莺一起鸣叫，像在交谈。" },
            { word: "燕双飞", pinyin: "yàn shuāng fēi", meaning: "两只燕子成双飞翔。" },
            { word: "窗前", pinyin: "chuāng qián", meaning: "窗户前面，离屋内较近。" },
            { word: "帘外", pinyin: "lián wài", meaning: "帘子外面，是更开阔的空间。" },
          ],
          pairing: "黄莺对燕子，窗前对帘外，一同鸣叫对成双飞翔；一边用耳朵听，一边用眼睛看。",
          storyTitle: NO_STORY_TITLE,
          story: "鸟儿并不真的说人话，“并语”是把连续鸣叫想象成伙伴聊天，让画面更亲切。",
        },
        {
          id: "wei-2-5",
          text: "汉致太平三尺剑，周臻大定一戎衣。",
          pinyin: "hàn zhì tài píng sān chǐ jiàn，zhōu zhēn dà dìng yì róng yī。",
          meaning: "旧说汉高祖凭三尺剑建立汉朝，周武王穿上军装完成伐纣，天下逐渐安定。",
          terms: [
            { word: "三尺剑", pinyin: "sān chǐ jiàn", meaning: "古人对长剑的常见说法，这里与汉高祖刘邦的故事相连。" },
            { word: "一戎衣", pinyin: "yì róng yī", meaning: "穿一次军装，借指周武王出兵。戎衣就是军服。" },
            { word: "致太平", pinyin: "zhì tài píng", meaning: "使社会走向安定。" },
            { word: "臻大定", pinyin: "zhēn dà dìng", meaning: "达到大体安定的局面。臻就是达到。" },
          ],
          pairing: "汉对周，剑对军服，建立太平对达到安定；两边都用一件军事器物概括王朝建立故事。",
          storyTitle: "短句背后是复杂历史",
          story: "历史上的安定不是一把剑或一件衣服就能带来，这里只是古人用器物浓缩漫长战争。学习历史要珍惜和平，不崇拜武器。",
        },
        {
          id: "wei-2-6",
          text: "吟成赏月之诗只愁月堕；斟满送春之酒惟憾春归。",
          pinyin: "yín chéng shǎng yuè zhī shī zhǐ chóu yuè duò；zhēn mǎn sòng chūn zhī jiǔ wéi hàn chūn guī。",
          meaning: "赏月诗刚写成，却担心月亮就要落下；送春宴饮刚准备好，又遗憾春天即将离去。",
          terms: [
            { word: "月堕", pinyin: "yuè duò", meaning: "月亮渐渐落到地平线下。" },
            { word: "春归", pinyin: "chūn guī", meaning: "春天过去，仿佛春天要回到别处。" },
            { word: "吟成", pinyin: "yín chéng", meaning: "吟咏、写成诗句。" },
            { word: "斟满", pinyin: "zhēn mǎn", meaning: "把饮品倒满杯子；儿童只理解古代宴饮场景。" },
          ],
          pairing: "赏月对送春，写诗对斟杯，月落对春归；两边都写美好时光将要结束时的珍惜。",
          storyTitle: "因为短暂，所以珍惜",
          story: "月亮会落，春天会走，但它们也会再来。古人写一点遗憾，是在提醒自己认真感受眼前的美好。",
        },
      ],
    },
    {
      title: "第三则 · 诗经与人物",
      sentences: [
        {
          id: "wei-3-1",
          text: "声对色，饱对饥，虎节对龙旗。",
          pinyin: "shēng duì sè，bǎo duì jī，hǔ jié duì lóng qí。",
          meaning: "耳朵听见的声音对眼睛看见的颜色，吃饱对饥饿，虎形符节对画龙旗帜。",
          terms: [
            { word: "声", pinyin: "shēng", meaning: "耳朵能够听见的声音。" },
            { word: "色", pinyin: "sè", meaning: "眼睛能够看见的颜色和形貌。" },
            { word: "虎节", pinyin: "hǔ jié", meaning: "古代做成虎形、供使者证明身份的符节。" },
            { word: "龙旗", pinyin: "lóng qí", meaning: "画有龙纹的旗帜。" },
          ],
          pairing: "听觉对视觉，满足对缺少，虎形信物对龙纹旗帜；三组分别来自感官、身体感受和古代器物。",
          storyTitle: "古代的身份凭证",
          story: "虎节有点像古代使者的身份证明，双方核对后才相信来人的身份。它提醒我们重要信息需要可靠凭证。",
        },
        {
          id: "wei-3-2",
          text: "杨花对桂叶，白简对朱衣。",
          pinyin: "yáng huā duì guì yè，bái jiǎn duì zhū yī。",
          meaning: "轻白杨花对深绿桂叶，记录意见的白色简板对官员红色衣服。",
          terms: [
            { word: "杨花", pinyin: "yáng huā", meaning: "杨树或柳树飘散的絮状种子，颜色轻白。" },
            { word: "桂叶", pinyin: "guì yè", meaning: "桂树常绿、带香气的叶片。" },
            { word: "白简", pinyin: "bái jiǎn", meaning: "古代官员写下弹劾或意见的白色简板。" },
            { word: "朱衣", pinyin: "zhū yī", meaning: "红色官服，朱就是红色。" },
          ],
          pairing: "轻花对常绿叶，白色简板对红色衣服；一组来自花木，一组来自古代官场，颜色也一白一红。",
          storyTitle: NO_STORY_TITLE,
          story: "古代官服颜色和官职有关，白简则用来写公务。今天判断一个人不能只看衣服颜色，而要看他的责任和行为。",
        },
        {
          id: "wei-3-3",
          text: "尨也吠，燕于飞，荡荡对巍巍。",
          pinyin: "máng yě fèi，yàn yú fēi，dàng dàng duì wēi wēi。",
          meaning: "长毛狗叫起来，燕子在天空飞翔；广阔平坦对高大耸立。",
          terms: [
            { word: "尨也吠", pinyin: "máng yě fèi", meaning: "长毛狗在叫，语意来自《诗经》中的句子。" },
            { word: "燕于飞", pinyin: "yàn yú fēi", meaning: "燕子飞翔，也让人想到《诗经·燕燕》。" },
            { word: "荡荡", pinyin: "dàng dàng", meaning: "广大开阔、平坦无边的样子。" },
            { word: "巍巍", pinyin: "wēi wēi", meaning: "山峰或建筑高大雄伟的样子。" },
          ],
          pairing: "狗在地上叫对燕在天上飞，开阔低平对高大耸立；一组有声有动作，一组比较空间形态。",
          storyTitle: "从《诗经》借来的声音和飞翔",
          story: "前两小句化用了古老诗歌中的词。作者把不同篇章里的狗吠和燕飞放在一起，让熟悉经典的人产生联想。",
        },
        {
          id: "wei-3-4",
          text: "春暄资日气，秋吟借霜威。",
          pinyin: "chūn xuān zī rì qì，qiū yín jiè shuāng wēi。",
          meaning: "春天的温暖来自日光滋养，秋日的吟咏借着寒霜显出清劲力量。",
          terms: [
            { word: "春暄", pinyin: "chūn xuān", meaning: "春天温暖和煦。暄就是温暖。" },
            { word: "秋吟", pinyin: "qiū yín", meaning: "秋日的吟咏，也可联想到秋虫鸣叫。" },
            { word: "日气", pinyin: "rì qì", meaning: "太阳带来的光和温暖。" },
            { word: "霜威", pinyin: "shuāng wēi", meaning: "寒霜带来的凛冽力量，威在这里写气势。" },
          ],
          pairing: "春对秋，暖阳对寒霜，温暖滋养对清寒增添力量；一柔一劲。",
          storyTitle: NO_STORY_TITLE,
          story: "太阳和霜并没有把东西“借”出去，作者把自然力量写成人的帮助，让季节更有性格。",
        },
        {
          id: "wei-3-5",
          text: "出使振威冯奉世，治民异等尹翁归。",
          pinyin: "chū shǐ zhèn wēi féng fèng shì，zhì mín yì děng yǐn wēng guī。",
          meaning: "冯奉世出使远方时果断处理危机，尹翁归治理地方时成绩突出。",
          terms: [
            { word: "冯奉世", pinyin: "féng fèng shì", meaning: "汉代使者和将领，出使时曾临机处理危急局面。" },
            { word: "尹翁归", pinyin: "yǐn wēng guī", meaning: "汉代官员，以熟悉地方情况、认真治理著称。" },
            { word: "出使", pinyin: "chū shǐ", meaning: "代表国家到远方办理事务。" },
            { word: "治民", pinyin: "zhì mín", meaning: "古代官员管理地方公共事务。" },
          ],
          pairing: "出使远方对治理地方，冯奉世对尹翁归，处理外部危机对做好内部事务；都强调承担责任。",
          storyTitle: "不同岗位的责任",
          story: "旧史常赞美两人的能力。给孩子学习的重点不是威风，而是遇到任务先了解情况、保护大家、认真完成职责。",
        },
        {
          id: "wei-3-6",
          text: "燕我弟兄载咏棣棠韡韡；命伊将帅为歌杨柳依依。",
          pinyin: "yàn wǒ dì xiōng zài yǒng dì táng wěi wěi；mìng yī jiàng shuài wéi gē yáng liǔ yī yī。",
          meaning: "宴请兄弟时吟唱棣棠花明丽的《常棣》，送将士远行时歌唱杨柳依依的《采薇》。",
          terms: [
            { word: "棣棠韡韡", pinyin: "dì táng wěi wěi", meaning: "棣棠花明丽茂盛，来自《诗经·常棣》，常用来表达兄弟亲情。" },
            { word: "杨柳依依", pinyin: "yáng liǔ yī yī", meaning: "杨柳柔软轻摇，来自《诗经·采薇》，带着远行时的留恋。" },
            { word: "燕我弟兄", pinyin: "yàn wǒ dì xiōng", meaning: "宴请、安乐自己的兄弟亲友。燕在这里读四声，通“宴”。" },
            { word: "命伊将帅", pinyin: "mìng yī jiàng shuài", meaning: "命令将士出发执行任务。伊在这里是语气或指示用字。" },
          ],
          pairing: "家人相聚对将士远行，棣棠花对杨柳，欢聚之歌对离别之歌；两边都借《诗经》表达感情。",
          storyTitle: "两首古老的歌",
          story: "《常棣》让人想到亲友相聚，《采薇》写远行者对家乡的思念。战争会带来分离，今天读它更应懂得珍惜家人和和平。",
        },
      ],
    },
  ],
} as const satisfies AnnotatedRhymeChapter;
