import type { AnnotatedRhymeChapter } from "./content";

const NO_STORY_TITLE = "这句没有专门故事";

export const RHYME_CHAPTER_FOUR = {
  id: "upper-4",
  title: "四支",
  volume: "上卷",
  focus: "从花木鸟兽、文房器物和古人故事里，理解每组词怎样从画面、动作或人物经历上相照。",
  sections: [
    {
      title: "第一则 · 花鸟与品格",
      sentences: [
        {
          id: "zhi-1-1",
          text: "茶对酒，赋对诗，燕子对莺儿。",
          pinyin: "chá duì jiǔ，fù duì shī，yàn zi duì yīng ér。",
          meaning: "茶饮对古代酒饮，辞赋对诗歌，燕子对黄莺。",
          terms: [
            { word: "茶", pinyin: "chá", meaning: "用茶叶冲泡的饮品。" },
            { word: "酒", pinyin: "jiǔ", meaning: "古代宴席和诗文中常见的饮品；儿童不能饮酒。" },
            { word: "赋", pinyin: "fù", meaning: "古代一种讲究铺陈描写的文章形式。" },
            { word: "诗", pinyin: "shī", meaning: "用有节奏的语言表达画面和感情的文学作品。" },
          ],
          pairing: "茶和酒都是饮品，赋和诗都是文学作品，燕子和黄莺都是春天常见的鸟。",
          storyTitle: NO_STORY_TITLE,
          story: "这句从舌尖的味道写到纸上的文字，再写到天空中的鸟，三组都很容易在生活或阅读中发现。",
        },
        {
          id: "zhi-1-2",
          text: "栽花对种竹，落絮对游丝。",
          pinyin: "zāi huā duì zhòng zhú，luò xù duì yóu sī。",
          meaning: "栽种花草对种植竹子，飘落的柳絮对空中细细飘游的蛛丝。",
          terms: [
            { word: "栽花", pinyin: "zāi huā", meaning: "把花苗种进土中照料。" },
            { word: "种竹", pinyin: "zhòng zhú", meaning: "种植竹子。这里“种”读四声。" },
            { word: "落絮", pinyin: "luò xù", meaning: "从柳树等植物上飘落的轻软绒絮。" },
            { word: "游丝", pinyin: "yóu sī", meaning: "春天空中飘动的细蛛丝，也可泛指细细飘丝。" },
          ],
          pairing: "种花对种竹，是人的栽植动作；柳絮对蛛丝，都是轻软、会随风飘动的细小事物。",
          storyTitle: NO_STORY_TITLE,
          story: "落絮和游丝很轻，风一吹就会移动。观察时只用眼睛看，不要追到车道或水边。",
        },
        {
          id: "zhi-1-3",
          text: "四目颉，一足夔，鸲鹆对鹭鸶。",
          pinyin: "sì mù jié，yì zú kuí，qú yù duì lù sī。",
          meaning: "传说仓颉有四只眼睛，夔只有一只脚；八哥对鹭鸶。",
          terms: [
            { word: "四目颉", pinyin: "sì mù jié", meaning: "古代传说把造字的仓颉画成四只眼睛，表示观察力非凡。" },
            { word: "一足夔", pinyin: "yì zú kuí", meaning: "古代传说中的夔常被描述为只有一只脚。" },
            { word: "鸲鹆", pinyin: "qú yù", meaning: "八哥，会模仿一些声音的黑色鸟。" },
            { word: "鹭鸶", pinyin: "lù sī", meaning: "鹭鸟，常在水边活动，羽毛多为白色。" },
          ],
          pairing: "四只眼对一只脚，传说人物对传说动物；黑色八哥对白色水鸟，又是一组真实鸟类。",
          storyTitle: "传说不等于真实样子",
          story: "仓颉四目和夔一足都是古人的神奇想象，用来突出他们不同寻常。读神话时可以大胆想象，也要知道它不是科学观察记录。",
        },
        {
          id: "zhi-1-4",
          text: "半池红菡萏，一架白荼縻。",
          pinyin: "bàn chí hóng hàn dàn，yí jià bái tú mí。",
          meaning: "半池红色荷花盛开，一架白色荼蘼花铺展开来。",
          terms: [
            { word: "菡萏", pinyin: "hàn dàn", meaning: "荷花的古称，这里写红色荷花。" },
            { word: "荼縻", pinyin: "tú mí", meaning: "也常写作荼蘼，一种开白花的攀援植物。" },
            { word: "半池", pinyin: "bàn chí", meaning: "半个池塘，表现水面花开很多。" },
            { word: "一架", pinyin: "yí jià", meaning: "一整座花架，表现藤花铺展。" },
          ],
          pairing: "池中荷花对架上藤花，红色对白色，半池水面花对一架攀援花。",
          storyTitle: NO_STORY_TITLE,
          story: "一边的花从水中挺起，一边的花沿架子攀爬，颜色和生长位置都形成清楚对照。",
        },
        {
          id: "zhi-1-5",
          text: "几阵秋风能应候，一犁春雨甚知时。",
          pinyin: "jǐ zhèn qiū fēng néng yìng hòu，yì lí chūn yǔ shèn zhī shí。",
          meaning: "几阵秋风顺着时节吹来，一场春雨正好在耕种需要时落下。",
          terms: [
            { word: "应候", pinyin: "yìng hòu", meaning: "顺应季节和气候的变化。" },
            { word: "知时", pinyin: "zhī shí", meaning: "仿佛懂得合适时节，这里赞美春雨来得及时。" },
            { word: "秋风", pinyin: "qiū fēng", meaning: "秋季吹起、常带来凉意的风。" },
            { word: "春雨", pinyin: "chūn yǔ", meaning: "春天的雨水，能帮助植物和庄稼生长。" },
          ],
          pairing: "秋风对春雨，几阵对一场，顺应时令对来得及时；两边都写天气和农时相配合。",
          storyTitle: "好雨知时节",
          story: "古人种田很依靠天气，所以特别珍惜及时的春雨。这里把风雨写得像懂得季节一样，是亲切的拟人想象。",
        },
        {
          id: "zhi-1-6",
          text: "智伯恩深国士吞变形之炭；羊公德大邑人竖堕泪之碑。",
          pinyin: "zhì bó ēn shēn guó shì tūn biàn xíng zhī tàn；yáng gōng dé dà yì rén shù duò lèi zhī bēi。",
          meaning: "豫让为报答智伯，曾用炭改变声音和样貌；羊祜爱护百姓，去世后人们立碑怀念，见碑落泪。",
          terms: [
            { word: "国士", pinyin: "guó shì", meaning: "这里指受到尊重、有才能和志向的人豫让。" },
            { word: "邑人", pinyin: "yì rén", meaning: "当地城邑中的百姓。" },
            { word: "变形之炭", pinyin: "biàn xíng zhī tàn", meaning: "故事说豫让吞炭改变声音、涂漆改变外貌。" },
            { word: "堕泪之碑", pinyin: "duò lèi zhī bēi", meaning: "人们纪念羊祜的石碑，因见碑思人而落泪。" },
          ],
          pairing: "豫让报答知遇对百姓怀念羊祜，一个用激烈行动表达，一个用纪念和眼泪表达。",
          storyTitle: "怎样表达感激与怀念",
          story: "豫让的做法带有古代复仇观念，不适合模仿；羊祜因善待百姓而被长久怀念。今天表达感激应选择安全、守法、珍惜生命的方式。",
        },
      ],
    },
    {
      title: "第二则 · 文房与旧事",
      sentences: [
        {
          id: "zhi-2-1",
          text: "行对止，速对迟，舞剑对围棋。",
          pinyin: "xíng duì zhǐ，sù duì chí，wǔ jiàn duì wéi qí。",
          meaning: "前进对停止，快速对缓慢，舞剑对下围棋。",
          terms: [
            { word: "行", pinyin: "xíng", meaning: "行走、前进。" },
            { word: "止", pinyin: "zhǐ", meaning: "停下来。" },
            { word: "舞剑", pinyin: "wǔ jiàn", meaning: "古代表演或练习剑术的动作。" },
            { word: "围棋", pinyin: "wéi qí", meaning: "黑白棋子在棋盘上围地的传统棋类游戏。" },
          ],
          pairing: "行动对停止，快对慢，身体活动对安静思考；三组都有明显不同的节奏。",
          storyTitle: "一动一静",
          story: "舞剑动作舒展，围棋需要安静思考。剑是古代器物，孩子不应拿尖锐物品模仿。",
        },
        {
          id: "zhi-2-2",
          text: "花笺对草字，竹简对毛锥。",
          pinyin: "huā jiān duì cǎo zì，zhú jiǎn duì máo zhuī。",
          meaning: "带花纹的信纸对潇洒草书，古代竹简对毛笔。",
          terms: [
            { word: "花笺", pinyin: "huā jiān", meaning: "带颜色或花纹、用来写信题诗的精美纸张。" },
            { word: "草字", pinyin: "cǎo zì", meaning: "书写连贯简省的草书字体。" },
            { word: "竹简", pinyin: "zhú jiǎn", meaning: "纸普及前，用来写字的一片片竹条。" },
            { word: "毛锥", pinyin: "máo zhuī", meaning: "毛笔的别称，因为笔头尖尖像锥。" },
          ],
          pairing: "写字的纸对字的写法，古老书写材料对书写工具；四样都与读书写字有关。",
          storyTitle: "文字写在哪里",
          story: "古人先在竹简上书写，后来纸张普及，花笺也变得精美。工具变化了，人们记录想法的愿望一直没有变。",
        },
        {
          id: "zhi-2-3",
          text: "汾水鼎，岘山碑，虎豹对熊罴。",
          pinyin: "fén shuǐ dǐng，xiàn shān bēi，hǔ bào duì xióng pí。",
          meaning: "汾水旁发现古鼎的故事对岘山纪念羊祜的石碑，虎豹对熊罴。",
          terms: [
            { word: "汾水鼎", pinyin: "fén shuǐ dǐng", meaning: "汉代在汾水一带得到古鼎的历史传说。" },
            { word: "岘山碑", pinyin: "xiàn shān bēi", meaning: "岘山上纪念羊祜、使人怀念落泪的碑。" },
            { word: "虎豹", pinyin: "hǔ bào", meaning: "老虎和豹子，两种大型猛兽。" },
            { word: "熊罴", pinyin: "xióng pí", meaning: "熊和罴；罴常解释为大熊或棕熊。" },
          ],
          pairing: "水边古鼎对山上石碑，虎豹对熊罴；前一组是历史器物，后一组是有力量的猛兽。",
          storyTitle: "鼎与碑记录往事",
          story: "鼎能让人想到古代礼仪，碑能记录人物和事件。它们像不会说话的历史讲解员。",
        },
        {
          id: "zhi-2-4",
          text: "花开红锦绣，水漾碧琉璃。",
          pinyin: "huā kāi hóng jǐn xiù，shuǐ yàng bì liú li。",
          meaning: "红花盛开，像铺开的锦绣；碧水荡漾，像透亮琉璃。",
          terms: [
            { word: "红锦绣", pinyin: "hóng jǐn xiù", meaning: "红色华美丝织品，这里比喻盛开的花。" },
            { word: "碧琉璃", pinyin: "bì liú li", meaning: "青绿色透明琉璃，这里比喻清澈水面。" },
            { word: "花开", pinyin: "huā kāi", meaning: "花朵展开，颜色显现。" },
            { word: "水漾", pinyin: "shuǐ yàng", meaning: "水面轻轻起波纹。" },
          ],
          pairing: "红花对碧水，锦绣对琉璃，花朵展开对水波荡漾；一边柔软鲜艳，一边清澈闪亮。",
          storyTitle: NO_STORY_TITLE,
          story: "作者没有真的把布和琉璃放进景色，而是借熟悉的颜色和光泽帮助我们想象花与水。",
        },
        {
          id: "zhi-2-5",
          text: "去妇因探邻舍枣，出妻为种后园葵。",
          pinyin: "qù fù yīn tān lín shè zǎo，chū qī wèi zhòng hòu yuán kuí。",
          meaning: "旧故事里，有女子因取邻家枣子被休弃，也有人因妻子在后园种葵菜而让她离开。",
          terms: [
            { word: "探邻舍枣", pinyin: "tān lín shè zǎo", meaning: "伸手取邻居家的枣子，故事把它看作不该拿别人物品。" },
            { word: "种后园葵", pinyin: "zhòng hòu yuán kuí", meaning: "在后园种葵菜；旧故事牵涉古代官员不与百姓争利的观念。" },
            { word: "去妇", pinyin: "qù fù", meaning: "古代被丈夫休弃、离开家庭的女子。" },
            { word: "出妻", pinyin: "chū qī", meaning: "古代男子让妻子离开，和“去妇”意思相近。" },
          ],
          pairing: "邻舍枣对后园葵，两件小事对两则旧故事，结果都是古代女子被迫离开家庭。",
          storyTitle: "看见故事里的不公平",
          story: "这些故事反映古代家庭权力不平等。拿别人东西应先征得同意，但不能因此认同随意赶走家人；今天处理错误要讲道理、尊重每个人。",
        },
        {
          id: "zhi-2-6",
          text: "笛韵和谐仙管恰从云里降；橹声咿轧渔舟正向雪中移。",
          pinyin: "dí yùn hé xié xiān guǎn qià cóng yún lǐ jiàng；lǔ shēng yī yà yú zhōu zhèng xiàng xuě zhōng yí。",
          meaning: "和谐笛声仿佛从云中仙境飘下，摇橹的咿轧声伴着渔船从雪中慢慢移来。",
          terms: [
            { word: "笛韵", pinyin: "dí yùn", meaning: "笛子吹出的悠扬声音。" },
            { word: "橹声", pinyin: "lǔ shēng", meaning: "船橹划水、转动时发出的声音。" },
            { word: "仙管", pinyin: "xiān guǎn", meaning: "像仙乐一样美妙的管乐声。" },
            { word: "渔舟", pinyin: "yú zhōu", meaning: "捕鱼人使用的小船。" },
          ],
          pairing: "云中笛声对雪中橹声，仙乐对渔舟，降下对移来；一个声音轻灵，一个声音朴实。",
          storyTitle: "两种远处的声音",
          story: "看不见吹笛人时，声音像从云中来；雪里先听到咿轧声，才看见船靠近。声音也能带我们认识远近。",
        },
      ],
    },
    {
      title: "第三则 · 动静与才学",
      sentences: [
        {
          id: "zhi-3-1",
          text: "戈对甲，鼓对旗，紫燕对黄鹂。",
          pinyin: "gē duì jiǎ，gǔ duì qí，zǐ yàn duì huáng lí。",
          meaning: "古代兵器戈对护身铠甲，战鼓对旗帜，紫燕对黄鹂。",
          terms: [
            { word: "戈", pinyin: "gē", meaning: "古代一种带横刃的长柄兵器。" },
            { word: "甲", pinyin: "jiǎ", meaning: "古代保护身体的铠甲。" },
            { word: "紫燕", pinyin: "zǐ yàn", meaning: "羽色深亮的燕子，也是诗文中对燕子的美称。" },
            { word: "黄鹂", pinyin: "huáng lí", meaning: "羽毛鲜黄、叫声清亮的鸟。" },
          ],
          pairing: "进攻器物对防护器物，鼓声对旗号，深色燕子对黄色黄鹂；前两组写古代队伍，后一组回到春日鸟儿。",
          storyTitle: "认识历史器物，不模仿打斗",
          story: "戈、甲、鼓、旗帮助我们看懂古代场景。孩子只把它们当历史知识，不拿尖锐物品当武器。",
        },
        {
          id: "zhi-3-2",
          text: "酸梅对李苦，青眼对白眉。",
          pinyin: "suān méi duì lǐ kǔ，qīng yǎn duì bái méi。",
          meaning: "味酸的梅子对味苦的李子，表示欣赏的青眼对马良眉中有白毛的白眉。",
          terms: [
            { word: "酸梅", pinyin: "suān méi", meaning: "带酸味的梅子。" },
            { word: "李苦", pinyin: "lǐ kǔ", meaning: "味道发苦的李子，也让人想到路边苦李的故事。" },
            { word: "青眼", pinyin: "qīng yǎn", meaning: "正眼相看，后来表示欣赏、重视。" },
            { word: "白眉", pinyin: "bái méi", meaning: "三国人物马良眉中有白毛，后来也用来称赞同辈中出众的人。" },
          ],
          pairing: "酸味对苦味，青眼对白眉；一组用嘴品尝，一组借眼眉讲人物态度和特点。",
          storyTitle: "青眼与白眉",
          story: "阮籍见到欣赏的人会用青眼正视；马良因眉中有白毛又很有才干，被称为“白眉”。今天尊重别人不看外貌，而看品格和行动。",
        },
        {
          id: "zhi-3-3",
          text: "三弄笛，一围棋，雨打对风吹。",
          pinyin: "sān nòng dí，yì wéi qí，yǔ dǎ duì fēng chuī。",
          meaning: "笛曲吹奏三段对下一局围棋，雨点敲打对风儿吹拂。",
          terms: [
            { word: "三弄笛", pinyin: "sān nòng dí", meaning: "笛曲反复分段吹奏，也让人想到《梅花三弄》。" },
            { word: "一围棋", pinyin: "yì wéi qí", meaning: "下一局围棋；围在这里作量词理解。" },
            { word: "雨打", pinyin: "yǔ dǎ", meaning: "雨点落下，像轻轻敲击物体。" },
            { word: "风吹", pinyin: "fēng chuī", meaning: "空气流动，吹动花木和衣物。" },
          ],
          pairing: "吹笛对下棋，三对一，雨点敲打对风儿吹动；既有人的活动，也有自然动作。",
          storyTitle: NO_STORY_TITLE,
          story: "“弄”在这里可以表示演奏，不是随便玩弄。一个常用字放进古文，也可能有新的意思。",
        },
        {
          id: "zhi-3-4",
          text: "海棠春睡早，杨柳昼眠迟。",
          pinyin: "hǎi táng chūn shuì zǎo，yáng liǔ zhòu mián chí。",
          meaning: "海棠在春日早早呈现慵懒姿态，杨柳到白天较晚时才像合眼休息。",
          terms: [
            { word: "海棠春睡", pinyin: "hǎi táng chūn shuì", meaning: "把海棠娇柔的样子想象成春天熟睡。" },
            { word: "杨柳昼眠", pinyin: "yáng liǔ zhòu mián", meaning: "把杨柳叶片昼间开合或下垂想象成睡觉。" },
            { word: "早", pinyin: "zǎo", meaning: "时间靠前。" },
            { word: "迟", pinyin: "chí", meaning: "时间靠后、较晚。" },
          ],
          pairing: "海棠对杨柳，春睡对昼眠，早对迟；两种植物都被写得像会睡觉的人。",
          storyTitle: "花木也会“睡觉”",
          story: "植物不会像人一样睡觉，但叶片和花朵会随光照、温度改变姿态。古人把这种变化写成“春睡”“昼眠”，既形象又有趣。",
        },
        {
          id: "zhi-3-5",
          text: "张骏曾为槐树赋，杜陵不做海棠诗。",
          pinyin: "zhāng jùn céng wéi huái shù fù，dù líng bù zuò hǎi táng shī。",
          meaning: "张骏曾写文章赞咏槐树，号称杜陵的杜甫却很少或没有专门写海棠诗。",
          terms: [
            { word: "张骏", pinyin: "zhāng jùn", meaning: "十六国时期前凉君主，旧注说他曾作《槐树赋》。" },
            { word: "杜陵", pinyin: "dù líng", meaning: "诗人杜甫的别称之一。" },
            { word: "槐树赋", pinyin: "huái shù fù", meaning: "用赋这种文体描写槐树的文章。" },
            { word: "海棠诗", pinyin: "hǎi táng shī", meaning: "以海棠为题或主要景物的诗。" },
          ],
          pairing: "张骏对杜甫，槐树对海棠，写赋对不作诗；两边都谈人物与植物文章。",
          storyTitle: "旧注里的文学小谜题",
          story: "后人发现杜甫诗中少见海棠，便产生多种猜想，但没有一种能完全确定。遇到没有定论的故事，要学会说“可能”，不要把猜想说成事实。",
        },
        {
          id: "zhi-3-6",
          text: "晋士特奇可比一斑之豹；唐儒博识堪为五总之龟。",
          pinyin: "jìn shì tè qí kě bǐ yì bān zhī bào；táng rú bó shí kān wéi wǔ zǒng zhī guī。",
          meaning: "晋代聪慧少年像从一个斑纹就能看出豹子不凡；唐代博学读书人像能汇总许多知识的灵龟。",
          terms: [
            { word: "一斑之豹", pinyin: "yì bān zhī bào", meaning: "从管中看豹虽只见一块斑纹，也能猜到整体不凡。" },
            { word: "五总之龟", pinyin: "wǔ zǒng zhī guī", meaning: "旧时称赞人博学多识的说法，像能总括许多知识。" },
            { word: "特奇", pinyin: "tè qí", meaning: "特别聪慧、不同寻常。" },
            { word: "博识", pinyin: "bó shí", meaning: "见闻广、懂得很多。" },
          ],
          pairing: "晋代少年对唐代学者，聪慧对博学，豹纹对灵龟；两边都借动物称赞人的才学。",
          storyTitle: "看见一点与知道很多",
          story: "“一斑”提醒我们一点细节能显出特点，但也不能只凭一点就武断决定全部；“博识”则来自长期阅读和观察。",
        },
      ],
    },
  ],
} as const satisfies AnnotatedRhymeChapter;
