"""300 authored subject combinations in the approved theme order.

The stage establishes shared physical relationships. Objects are constructed
from editable primitives, never looked up in the legacy sticker catalogue.
"""
GROUPS = [
'''night|telescope,pine,moon,backpack
bench|magnet,key,blocks,box
bench|flashlight,ball,board,mirror
bench|beaker,rock,boat,water-drop
field|windsock,thermometer,rain-cloud,bucket
bench|ramp,ball,box,blocks
bench|gear,gear,key,ruler
workshop|pulley,box,crane,glove
bench|scale,apple,blocks,plate
bench|drum,bell,wind,paper
bench|mirror,flashlight,board,arrow
bench|magnifier,seed,leaf,book
field|windmill,gear,house,wind
river|waterwheel,bridge,house,tree
field|paperplane,sign,hoop,blocks''',
'''bench|water-molecule,co2,crystal,book
display|crystal,ice,rock,magnifier
diagram|ice,water-drop,cloud
field|strata,crystal,tray,sun
bench|funnel,beaker,rock,paper
diagram|particles,ice,bubble-jar
bench|bubble-jar,dropper,bottle,book
display|blocks,spoon,cup,box
diagram|water-drop,water-molecule,magnifier
bench|test-tubes,dropper,beaker,rack
bench|beaker,ice,spoon,plate
bench|branch,crystal,tray,dropper
bench|ice,tray,sun,water-drop
display|atom,particles,crystal,frame
bench|molecule,co2,water-molecule,box''',
'''garden|flower,butterfly,sunflower,leaf
garden|sunflower,bee,box,flower
garden|leaf,ladybug,water-drop,flower
pond|lotus,dragonfly,leaf,seaweed
field|ant,seed,cave,leaf
garden|branch,caterpillar,sapling,leaf
cycle|egg,caterpillar,seed,butterfly
garden|bamboo,stick-insect,leaf,rock
garden|leaf,mantis,rock,flower
field|tree,cicada,leaf,stump
night|firefly,pine,moon,leaf
field|beetle,acorn,leaf,stump
garden|grasshopper,leaf,mushroom,rock
display|box,bamboo,bee,beetle
underground|ant,seed,box,root''',
'''diagram|person,hand,foot
diagram|skeleton,hand,foot
diagram|heart-organ,branch,water-drop
diagram|lungs,branch,person
diagram|stomach,intestine,spoon
diagram|hand,magnifier,leaf
field|foot,foot,sign,hoop
bench|tooth,toothbrush,cup,soap
bench|hand,soap,water-drop,towel
diagram|ear,drum,wind
diagram|nose,flower,wind
diagram|eye,telescope,window
diagram|person,ball,hoop
room|bed,moon,person,clock
bench|bottle,towel,boot,ball''',
'''island|volcano,rock,water-drop,sun
river|mountain,bridge,tree,rock
desert|dune,sign,palm,rock
river|glacier,iceberg,ice,mountain
river|cliff,bridge,rock,backpack
river|cliff,water-drop,rock,fern
island|bridge,rock,shell,fish
underground|cave,crystal,rock,lantern
terraces|mountain,house,sapling,wheat
underground|strata,fossil,root,rock
island|palm,coral,shell,boat
desert|rock,cliff,winter-tree,dune
pond|seaweed,duck,leaf,water-drop
delta|waterwheel,sailboat,palm,rock
diagram|earth-cut,ice,rock''',
'''city|robot,house,gear,blocks
sky|post-office,cloud,envelope,balloon
garden|mushroom,house,flower,leaf
sky|train,moon,ball,cloud
field|dragon,cave,egg,mountain
water|castle,submarine,gear,coral
island|treehouse,vine,bridge,cloud
sky|robot,rocket,moon,blocks
bench|gear,robot,key,box
field|castle,balloon,sign,tree
display|horse,robot,key,gear
field|tree,book,ladder,flower
water|castle,shell,drum,coral
night|person,tent,flag,moon
sky|spaceship,blocks,satellite,rocket''',
'''garden|house,flower,person,watering-can
bench|plate,bread,cup,egg
room|sofa,shelf,book,person
laundry|towel,person,planter,boot
room|cabinet,pot,bowl,pan
room|bed,clock,book,window
picnic|basket,apple,sandwich,cup
room|house,cat,dog,bowl
room|box,blocks,ball,puzzle
window|sapling,planter,seed,watering-can
room|washing-machine,basket,towel,soap
room|door,shelf,boot,mat
bench|kettle,cup,person,book
display|person,person,frame,flower
field|truck,box,lantern,cart''',
'''field|school,person,backpack,tree
room|desk,book,pencil,backpack
room|shelf,desk,book,person
room|easel,brush,palette,frame
room|drum,piano,bell,book
room|blocks,cabinet,ball,mat
field|person,hoop,ball,sign
display|fossil,magnifier,sapling,crystal
bench|plate,spoon,apple,cup
room|bed,bed,window,clock
window|shelf,planter,flower,watering-can
field|person,umbrella,rain-cloud,boot
room|rack,backpack,boot,box
room|board,broom,bucket,clock
road|bus,sign,person,school''',
'''night|tent,pine,moon,lantern
field|cabin,pine,stump,backpack
field|gazebo,mountain,telescope,sign
river|rock,bridge,backpack,tree
field|tent,sleeping-bag,boot,lantern
picnic|bread,cup,kettle,basket
forest|hammock,tree,book,backpack
field|tent,rain-cloud,umbrella,boot
field|mountain,sign,backpack,pine
bench|compass,map,rock,lantern
bench|bucket,soap,towel,water-drop
forest|telescope,duck,house,branch
bench|book,leaf,magnifier,acorn
island|bus,tent,shell,palm
field|cart,backpack,sleeping-bag,tent''',
'''cycle|sapling,tree,apple-tree,winter-tree
sequence|seed,sprout,sapling,tree
underground|root,tree,rock,seed
forest|fern,rock,mushroom,leaf
forest|bamboo,gazebo,leaf,wind
forest|tree,squirrel,acorn,leaf
field|pine,pinecone,rock,mountain
window|leaf,vine,rain-cloud,water-drop
bench|stump,leaf,magnifier,acorn
garden|rock,fern,leaf,mushroom
forest|mushroom,stump,leaf,fern
garden|bridge,vine,flower,planter
night|winter-tree,snowflake,house,moon
diagram|flower,leaf,seed
display|apple,seed,pumpkin,lemon''',
'''water|coral,seahorse,jellyfish,shell
island|lighthouse,sailboat,rock,shell
pond|starfish,shell,rock,crab
water|whale,fish,seaweed,water-drop
water|turtle,coral,rock,seaweed
island|crab,cave,shell,palm
river|sailboat,bridge,sign,bucket
water|submarine,fish,seaweed,shell
water|jellyfish,jellyfish,water-drop,coral
water|seahorse,seaweed,rock,shell
display|shell,crystal,starfish,magnifier
island|bottle,palm,water-drop,shell
water|bridge,coral,fish,seaweed
pond|sailboat,lotus,leaf,dragonfly
pond|duck,duck,seaweed,tree''',
'''garden|rabbit,carrot,cabbage,fence
forest|fox,tree,mushroom,leaf
forest|treehouse,squirrel,acorn,branch
river|deer,tree,leaf,rock
field|sheep,house,fence,wheat
pond|pig,tent,leaf,rock
field|house,chicken,seed,wheat
field|dog,person,bench,tree
window|cat,planter,flower,book
forest|hedgehog,leaf,root,stump
pond|turtle,rock,leaf,water-drop
island|penguin,iceberg,ice,snowflake
pond|elephant,palm,leaf,rock
field|giraffe,tree,leaf,sun
forest|bear,cave,pine,rock''',
'''radial|flower,ball,leaf,blocks
mosaic|blocks,crystal,ice,leaf
display|leaf,fern,book,magnifier
radial|butterfly,flower,leaf,ball
city|house,ball,bridge,moon
field|mountain,pine,sun,blocks
bench|vase,flower,ruler,brush
quilt|flower,leaf,ball,blocks
radial|shell,ball,starfish,leaf
radial|leaf,flower,vine,ball
quilt|flower,crystal,leaf,window
field|rock,leaf,ball,fern
display|ball,blocks,crystal,box
garden|flower,lotus,tulip,planter
mosaic|wind,water-drop,rock,ball''',
'''stage|drum,drum,bell,person
room|piano,bench,book,clock
bench|violin,box,book,ruler
garden|harp,flower,bench,leaf
forest|tree,bell,flag,flower
room|dancer,mirror,bench,book
stage|puppet,person,box,flag
bench|vase,plate,brush,rolling-pin
display|sculpture,blocks,frame,crystal
bench|paper,rolling-pin,brush,board
display|frame,easel,paper,palette
bench|flower,paper,scissors,planter
bench|loom,spool,scissors,ruler
bench|music-box,gear,key,ball
stage|gazebo,drum,bench,flower''',
'''field|kite,person,leaf,sun
field|hoop,ball,bottle,person
island|sandcastle,bucket,shovel,shell
forest|swing,tree,flower,ball
field|slide,ladder,ball,tree
field|chess,rock,boot,person
bench|bridge,blocks,car,ruler
bench|puzzle,box,book,blocks
bench|top,hoop,ball,box
bench|maze,ball,box,ruler
field|hoop,boot,towel,person
room|horse,blocks,window,ball
garden|cart,bear,flower,tree
river|paperboat,bridge,rock,leaf
bench|skate,helmet,glove,boot''',
'''crossing|train,mountain,bridge,pine
road|bus,sign,house,person
workshop|bicycle,key,pump,rack
field|airplane,house,flag,sign
field|helicopter,mountain,person,box
sky|balloon,balloon,cloud,house
river|crane,sailboat,box,truck
river|bridge,rock,tree,sailboat
field|excavator,rock,fence,helmet
terraces|tractor,wheat,house,leaf
workshop|car,water-drop,brush,door
crossing|train,house,bridge,sign
workshop|windmill-blades,windmill,key,gear
workshop|sailboat,rack,flag,box
road|car,bus,sign,person''',
'''sky|rover,rock,flag,moon
sky|rocket,crane,cloud,sign
orbit|sun,ball,moon,ice
sky|space-station,satellite,rocket,moon
room|astronaut,helmet,glove,boot
sky|saturn,satellite,moon,rocket
bench|rock,tray,magnifier,crystal
sky|comet,moon,ball,rocket
sequence|moon,ball,moon,window
sky|rocket,igloo,rover,satellite
sky|greenhouse,sapling,bottle,satellite
sky|satellite,ball,moon,cloud
constellation|ball,moon,compass,frame
window|ball,cloud,satellite,moon
sky|balloon,spaceship,cloud,mountain''',
'''garden|umbrella,flower,rain-cloud,water-drop
field|tree,bench,sun,ball
field|leaf,boot,wind,tree
night|igloo,snowflake,pine,moon
field|rainbow,mountain,cloud,flower
display|snowflake,snowflake,window,leaf
laundry|towel,windsock,wind,boot
window|rain-cloud,water-drop,bucket,cloud
forest|tree,wind,fern,water-drop
window|snowflake,leaf,crystal,ice
field|gazebo,ice,snow-cloud,bucket
pair|sun,rain-cloud,planter,flower
quarters|sapling,tree,apple-tree,winter-tree
field|snowman,towel,hat,snowflake
field|kite,windsock,sign,wind''',
'''orchard|apple-tree,ladder,basket,apple
garden|strawberry,basket,leaf,shovel
field|pumpkin,house,cart,leaf
bench|bread,rolling-pin,tray,flour
display|carrot,cabbage,tomato,basket
display|watermelon,lemon,apple,tray
bench|bottle,cup,bread,egg
terraces|wheat,water-drop,bridge,leaf
bench|corn,basket,seed,plate
garden|grapes,vine,leaf,basket
bench|noodles,rolling-pin,bowl,flour
bench|dumpling,plate,rolling-pin,bowl
picnic|sandwich,cabbage,box,cup
market|apple,basket,scale,shop
garden|greenhouse,sapling,watering-can,carrot''',
'''city|fountain,bench,house,tree
room|mailbox,envelope,rack,box
road|fire-station,firetruck,helmet,lantern
room|hospital,person,desk,box
window|bread,shelf,shop,sign
garden|gazebo,shelf,bench,book
city|house,clock,flower,sign
river|house,waterwheel,bridge,tree
island|lighthouse,ladder,rock,shell
field|windmill,mountain,flower,pine
garden|fountain,tree,bench,flower
garden|house,shelf,flower,bucket
forest|treehouse,ladder,branch,leaf
night|igloo,ice,snowflake,pine
field|recycle-bin,box,bottle,paper''',
]

# Small recipe vocabulary aliases describe simple constructions, not images.
ALIASES = {'boat':'sailboat','mat':'chess','flour':'box'}


def recipes():
    assert len(GROUPS)==20
    rows=[]
    for group in GROUPS:
        lines=group.splitlines()
        assert len(lines)==15
        for line in lines:
            stage,objects=line.split('|')
            rows.append((stage,[ALIASES.get(n,n) for n in objects.split(',')]))
    assert len(rows)==300
    return rows
