// Generated from PubChem PUG REST Periodic Table data.
// Source: https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON
// Chinese names follow the Chinese Chemical Society / IUPAC Chinese periodic table.
// Run: curl -fsSL https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON | node scripts/generate-periodic-table.mjs

export type ElementCategory =
  | "alkali-metal"
  | "alkaline-earth"
  | "transition-metal"
  | "post-transition-metal"
  | "metalloid"
  | "nonmetal"
  | "halogen"
  | "noble-gas"
  | "lanthanide"
  | "actinide";

export interface PeriodicElementRecord {
  atomicNumber: number;
  symbol: string;
  englishName: string;
  chineseName: string;
  pinyin: string;
  atomicMass: string;
  electronConfiguration: string;
  shells: readonly number[];
  electronegativity: string | null;
  atomicRadius: string | null;
  ionizationEnergy: string | null;
  electronAffinity: string | null;
  oxidationStates: string | null;
  standardState: string | null;
  meltingPoint: string | null;
  boilingPoint: string | null;
  density: string | null;
  category: ElementCategory;
  categoryLabel: string;
  yearDiscovered: string | null;
  period: number;
  group: number | null;
  displayRow: number;
  displayColumn: number;
}

export const ELEMENTS: readonly PeriodicElementRecord[] = [
  {
    "atomicNumber": 1,
    "symbol": "H",
    "englishName": "Hydrogen",
    "chineseName": "氢",
    "pinyin": "qīng",
    "atomicMass": "1.0080",
    "electronConfiguration": "1s1",
    "shells": [
      1
    ],
    "electronegativity": "2.2",
    "atomicRadius": "120",
    "ionizationEnergy": "13.598",
    "electronAffinity": "0.754",
    "oxidationStates": "+1, -1",
    "standardState": "Gas",
    "meltingPoint": "13.81",
    "boilingPoint": "20.28",
    "density": "0.00008988",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "1766",
    "period": 1,
    "group": 1,
    "displayRow": 1,
    "displayColumn": 1
  },
  {
    "atomicNumber": 2,
    "symbol": "He",
    "englishName": "Helium",
    "chineseName": "氦",
    "pinyin": "hài",
    "atomicMass": "4.00260",
    "electronConfiguration": "1s2",
    "shells": [
      2
    ],
    "electronegativity": null,
    "atomicRadius": "140",
    "ionizationEnergy": "24.587",
    "electronAffinity": null,
    "oxidationStates": "0",
    "standardState": "Gas",
    "meltingPoint": "0.95",
    "boilingPoint": "4.22",
    "density": "0.0001785",
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "1868",
    "period": 1,
    "group": 18,
    "displayRow": 1,
    "displayColumn": 18
  },
  {
    "atomicNumber": 3,
    "symbol": "Li",
    "englishName": "Lithium",
    "chineseName": "锂",
    "pinyin": "lǐ",
    "atomicMass": "7.0",
    "electronConfiguration": "[He]2s1",
    "shells": [
      2,
      1
    ],
    "electronegativity": "0.98",
    "atomicRadius": "182",
    "ionizationEnergy": "5.392",
    "electronAffinity": "0.618",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "453.65",
    "boilingPoint": "1615",
    "density": "0.534",
    "category": "alkali-metal",
    "categoryLabel": "碱金属",
    "yearDiscovered": "1817",
    "period": 2,
    "group": 1,
    "displayRow": 2,
    "displayColumn": 1
  },
  {
    "atomicNumber": 4,
    "symbol": "Be",
    "englishName": "Beryllium",
    "chineseName": "铍",
    "pinyin": "pí",
    "atomicMass": "9.012183",
    "electronConfiguration": "[He]2s2",
    "shells": [
      2,
      2
    ],
    "electronegativity": "1.57",
    "atomicRadius": "153",
    "ionizationEnergy": "9.323",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "1560",
    "boilingPoint": "2744",
    "density": "1.85",
    "category": "alkaline-earth",
    "categoryLabel": "碱土金属",
    "yearDiscovered": "1798",
    "period": 2,
    "group": 2,
    "displayRow": 2,
    "displayColumn": 2
  },
  {
    "atomicNumber": 5,
    "symbol": "B",
    "englishName": "Boron",
    "chineseName": "硼",
    "pinyin": "péng",
    "atomicMass": "10.81",
    "electronConfiguration": "[He]2s2 2p1",
    "shells": [
      2,
      3
    ],
    "electronegativity": "2.04",
    "atomicRadius": "192",
    "ionizationEnergy": "8.298",
    "electronAffinity": "0.277",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "2348",
    "boilingPoint": "4273",
    "density": "2.37",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "1808",
    "period": 2,
    "group": 13,
    "displayRow": 2,
    "displayColumn": 13
  },
  {
    "atomicNumber": 6,
    "symbol": "C",
    "englishName": "Carbon",
    "chineseName": "碳",
    "pinyin": "tàn",
    "atomicMass": "12.011",
    "electronConfiguration": "[He]2s2 2p2",
    "shells": [
      2,
      4
    ],
    "electronegativity": "2.55",
    "atomicRadius": "170",
    "ionizationEnergy": "11.260",
    "electronAffinity": "1.263",
    "oxidationStates": "+4, +2, -4",
    "standardState": "Solid",
    "meltingPoint": "3823",
    "boilingPoint": "4098",
    "density": "2.2670",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "Ancient",
    "period": 2,
    "group": 14,
    "displayRow": 2,
    "displayColumn": 14
  },
  {
    "atomicNumber": 7,
    "symbol": "N",
    "englishName": "Nitrogen",
    "chineseName": "氮",
    "pinyin": "dàn",
    "atomicMass": "14.007",
    "electronConfiguration": "[He] 2s2 2p3",
    "shells": [
      2,
      5
    ],
    "electronegativity": "3.04",
    "atomicRadius": "155",
    "ionizationEnergy": "14.534",
    "electronAffinity": null,
    "oxidationStates": "+5, +4, +3, +2, +1, -1, -2, -3",
    "standardState": "Gas",
    "meltingPoint": "63.15",
    "boilingPoint": "77.36",
    "density": "0.0012506",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "1772",
    "period": 2,
    "group": 15,
    "displayRow": 2,
    "displayColumn": 15
  },
  {
    "atomicNumber": 8,
    "symbol": "O",
    "englishName": "Oxygen",
    "chineseName": "氧",
    "pinyin": "yǎng",
    "atomicMass": "15.999",
    "electronConfiguration": "[He]2s2 2p4",
    "shells": [
      2,
      6
    ],
    "electronegativity": "3.44",
    "atomicRadius": "152",
    "ionizationEnergy": "13.618",
    "electronAffinity": "1.461",
    "oxidationStates": "-2",
    "standardState": "Gas",
    "meltingPoint": "54.36",
    "boilingPoint": "90.2",
    "density": "0.001429",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "1774",
    "period": 2,
    "group": 16,
    "displayRow": 2,
    "displayColumn": 16
  },
  {
    "atomicNumber": 9,
    "symbol": "F",
    "englishName": "Fluorine",
    "chineseName": "氟",
    "pinyin": "fú",
    "atomicMass": "18.99840316",
    "electronConfiguration": "[He]2s2 2p5",
    "shells": [
      2,
      7
    ],
    "electronegativity": "3.98",
    "atomicRadius": "135",
    "ionizationEnergy": "17.423",
    "electronAffinity": "3.339",
    "oxidationStates": "-1",
    "standardState": "Gas",
    "meltingPoint": "53.53",
    "boilingPoint": "85.03",
    "density": "0.001696",
    "category": "halogen",
    "categoryLabel": "卤素",
    "yearDiscovered": "1670",
    "period": 2,
    "group": 17,
    "displayRow": 2,
    "displayColumn": 17
  },
  {
    "atomicNumber": 10,
    "symbol": "Ne",
    "englishName": "Neon",
    "chineseName": "氖",
    "pinyin": "nǎi",
    "atomicMass": "20.180",
    "electronConfiguration": "[He]2s2 2p6",
    "shells": [
      2,
      8
    ],
    "electronegativity": null,
    "atomicRadius": "154",
    "ionizationEnergy": "21.565",
    "electronAffinity": null,
    "oxidationStates": "0",
    "standardState": "Gas",
    "meltingPoint": "24.56",
    "boilingPoint": "27.07",
    "density": "0.0008999",
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "1898",
    "period": 2,
    "group": 18,
    "displayRow": 2,
    "displayColumn": 18
  },
  {
    "atomicNumber": 11,
    "symbol": "Na",
    "englishName": "Sodium",
    "chineseName": "钠",
    "pinyin": "nà",
    "atomicMass": "22.9897693",
    "electronConfiguration": "[Ne]3s1",
    "shells": [
      2,
      8,
      1
    ],
    "electronegativity": "0.93",
    "atomicRadius": "227",
    "ionizationEnergy": "5.139",
    "electronAffinity": "0.548",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "370.95",
    "boilingPoint": "1156",
    "density": "0.97",
    "category": "alkali-metal",
    "categoryLabel": "碱金属",
    "yearDiscovered": "1807",
    "period": 3,
    "group": 1,
    "displayRow": 3,
    "displayColumn": 1
  },
  {
    "atomicNumber": 12,
    "symbol": "Mg",
    "englishName": "Magnesium",
    "chineseName": "镁",
    "pinyin": "měi",
    "atomicMass": "24.305",
    "electronConfiguration": "[Ne]3s2",
    "shells": [
      2,
      8,
      2
    ],
    "electronegativity": "1.31",
    "atomicRadius": "173",
    "ionizationEnergy": "7.646",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "923",
    "boilingPoint": "1363",
    "density": "1.74",
    "category": "alkaline-earth",
    "categoryLabel": "碱土金属",
    "yearDiscovered": "1808",
    "period": 3,
    "group": 2,
    "displayRow": 3,
    "displayColumn": 2
  },
  {
    "atomicNumber": 13,
    "symbol": "Al",
    "englishName": "Aluminum",
    "chineseName": "铝",
    "pinyin": "lǚ",
    "atomicMass": "26.981538",
    "electronConfiguration": "[Ne]3s2 3p1",
    "shells": [
      2,
      8,
      3
    ],
    "electronegativity": "1.61",
    "atomicRadius": "184",
    "ionizationEnergy": "5.986",
    "electronAffinity": "0.441",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "933.437",
    "boilingPoint": "2792",
    "density": "2.70",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "Ancient",
    "period": 3,
    "group": 13,
    "displayRow": 3,
    "displayColumn": 13
  },
  {
    "atomicNumber": 14,
    "symbol": "Si",
    "englishName": "Silicon",
    "chineseName": "硅",
    "pinyin": "guī",
    "atomicMass": "28.085",
    "electronConfiguration": "[Ne]3s2 3p2",
    "shells": [
      2,
      8,
      4
    ],
    "electronegativity": "1.9",
    "atomicRadius": "210",
    "ionizationEnergy": "8.152",
    "electronAffinity": "1.385",
    "oxidationStates": "+4, +2, -4",
    "standardState": "Solid",
    "meltingPoint": "1687",
    "boilingPoint": "3538",
    "density": "2.3296",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "1854",
    "period": 3,
    "group": 14,
    "displayRow": 3,
    "displayColumn": 14
  },
  {
    "atomicNumber": 15,
    "symbol": "P",
    "englishName": "Phosphorus",
    "chineseName": "磷",
    "pinyin": "lín",
    "atomicMass": "30.97376200",
    "electronConfiguration": "[Ne]3s2 3p3",
    "shells": [
      2,
      8,
      5
    ],
    "electronegativity": "2.19",
    "atomicRadius": "180",
    "ionizationEnergy": "10.487",
    "electronAffinity": "0.746",
    "oxidationStates": "+5, +3, -3",
    "standardState": "Solid",
    "meltingPoint": "317.3",
    "boilingPoint": "553.65",
    "density": "1.82",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "1669",
    "period": 3,
    "group": 15,
    "displayRow": 3,
    "displayColumn": 15
  },
  {
    "atomicNumber": 16,
    "symbol": "S",
    "englishName": "Sulfur",
    "chineseName": "硫",
    "pinyin": "liú",
    "atomicMass": "32.07",
    "electronConfiguration": "[Ne]3s2 3p4",
    "shells": [
      2,
      8,
      6
    ],
    "electronegativity": "2.58",
    "atomicRadius": "180",
    "ionizationEnergy": "10.360",
    "electronAffinity": "2.077",
    "oxidationStates": "+6, +4, -2",
    "standardState": "Solid",
    "meltingPoint": "388.36",
    "boilingPoint": "717.75",
    "density": "2.067",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "Ancient",
    "period": 3,
    "group": 16,
    "displayRow": 3,
    "displayColumn": 16
  },
  {
    "atomicNumber": 17,
    "symbol": "Cl",
    "englishName": "Chlorine",
    "chineseName": "氯",
    "pinyin": "lǜ",
    "atomicMass": "35.45",
    "electronConfiguration": "[Ne]3s2 3p5",
    "shells": [
      2,
      8,
      7
    ],
    "electronegativity": "3.16",
    "atomicRadius": "175",
    "ionizationEnergy": "12.968",
    "electronAffinity": "3.617",
    "oxidationStates": "+7, +5, +1, -1",
    "standardState": "Gas",
    "meltingPoint": "171.65",
    "boilingPoint": "239.11",
    "density": "0.003214",
    "category": "halogen",
    "categoryLabel": "卤素",
    "yearDiscovered": "1774",
    "period": 3,
    "group": 17,
    "displayRow": 3,
    "displayColumn": 17
  },
  {
    "atomicNumber": 18,
    "symbol": "Ar",
    "englishName": "Argon",
    "chineseName": "氩",
    "pinyin": "yà",
    "atomicMass": "39.9",
    "electronConfiguration": "[Ne]3s2 3p6",
    "shells": [
      2,
      8,
      8
    ],
    "electronegativity": null,
    "atomicRadius": "188",
    "ionizationEnergy": "15.760",
    "electronAffinity": null,
    "oxidationStates": "0",
    "standardState": "Gas",
    "meltingPoint": "83.8",
    "boilingPoint": "87.3",
    "density": "0.0017837",
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "1894",
    "period": 3,
    "group": 18,
    "displayRow": 3,
    "displayColumn": 18
  },
  {
    "atomicNumber": 19,
    "symbol": "K",
    "englishName": "Potassium",
    "chineseName": "钾",
    "pinyin": "jiǎ",
    "atomicMass": "39.0983",
    "electronConfiguration": "[Ar]4s1",
    "shells": [
      2,
      8,
      8,
      1
    ],
    "electronegativity": "0.82",
    "atomicRadius": "275",
    "ionizationEnergy": "4.341",
    "electronAffinity": "0.501",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "336.53",
    "boilingPoint": "1032",
    "density": "0.89",
    "category": "alkali-metal",
    "categoryLabel": "碱金属",
    "yearDiscovered": "1807",
    "period": 4,
    "group": 1,
    "displayRow": 4,
    "displayColumn": 1
  },
  {
    "atomicNumber": 20,
    "symbol": "Ca",
    "englishName": "Calcium",
    "chineseName": "钙",
    "pinyin": "gài",
    "atomicMass": "40.08",
    "electronConfiguration": "[Ar]4s2",
    "shells": [
      2,
      8,
      8,
      2
    ],
    "electronegativity": "1",
    "atomicRadius": "231",
    "ionizationEnergy": "6.113",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "1115",
    "boilingPoint": "1757",
    "density": "1.54",
    "category": "alkaline-earth",
    "categoryLabel": "碱土金属",
    "yearDiscovered": "Ancient",
    "period": 4,
    "group": 2,
    "displayRow": 4,
    "displayColumn": 2
  },
  {
    "atomicNumber": 21,
    "symbol": "Sc",
    "englishName": "Scandium",
    "chineseName": "钪",
    "pinyin": "kàng",
    "atomicMass": "44.95591",
    "electronConfiguration": "[Ar]4s2 3d1",
    "shells": [
      2,
      8,
      9,
      2
    ],
    "electronegativity": "1.36",
    "atomicRadius": "211",
    "ionizationEnergy": "6.561",
    "electronAffinity": "0.188",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1814",
    "boilingPoint": "3109",
    "density": "2.99",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1879",
    "period": 4,
    "group": 3,
    "displayRow": 4,
    "displayColumn": 3
  },
  {
    "atomicNumber": 22,
    "symbol": "Ti",
    "englishName": "Titanium",
    "chineseName": "钛",
    "pinyin": "tài",
    "atomicMass": "47.867",
    "electronConfiguration": "[Ar]4s2 3d2",
    "shells": [
      2,
      8,
      10,
      2
    ],
    "electronegativity": "1.54",
    "atomicRadius": "187",
    "ionizationEnergy": "6.828",
    "electronAffinity": "0.079",
    "oxidationStates": "+4, +3, +2",
    "standardState": "Solid",
    "meltingPoint": "1941",
    "boilingPoint": "3560",
    "density": "4.5",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1791",
    "period": 4,
    "group": 4,
    "displayRow": 4,
    "displayColumn": 4
  },
  {
    "atomicNumber": 23,
    "symbol": "V",
    "englishName": "Vanadium",
    "chineseName": "钒",
    "pinyin": "fán",
    "atomicMass": "50.9415",
    "electronConfiguration": "[Ar]4s2 3d3",
    "shells": [
      2,
      8,
      11,
      2
    ],
    "electronegativity": "1.63",
    "atomicRadius": "179",
    "ionizationEnergy": "6.746",
    "electronAffinity": "0.525",
    "oxidationStates": "+5, +4, +3, +2",
    "standardState": "Solid",
    "meltingPoint": "2183",
    "boilingPoint": "3680",
    "density": "6.0",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1801",
    "period": 4,
    "group": 5,
    "displayRow": 4,
    "displayColumn": 5
  },
  {
    "atomicNumber": 24,
    "symbol": "Cr",
    "englishName": "Chromium",
    "chineseName": "铬",
    "pinyin": "gè",
    "atomicMass": "51.996",
    "electronConfiguration": "[Ar]3d5 4s1",
    "shells": [
      2,
      8,
      13,
      1
    ],
    "electronegativity": "1.66",
    "atomicRadius": "189",
    "ionizationEnergy": "6.767",
    "electronAffinity": "0.666",
    "oxidationStates": "+6, +3, +2",
    "standardState": "Solid",
    "meltingPoint": "2180",
    "boilingPoint": "2944",
    "density": "7.15",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1797",
    "period": 4,
    "group": 6,
    "displayRow": 4,
    "displayColumn": 6
  },
  {
    "atomicNumber": 25,
    "symbol": "Mn",
    "englishName": "Manganese",
    "chineseName": "锰",
    "pinyin": "měng",
    "atomicMass": "54.93804",
    "electronConfiguration": "[Ar]4s2 3d5",
    "shells": [
      2,
      8,
      13,
      2
    ],
    "electronegativity": "1.55",
    "atomicRadius": "197",
    "ionizationEnergy": "7.434",
    "electronAffinity": null,
    "oxidationStates": "+7, +4, +3, +2",
    "standardState": "Solid",
    "meltingPoint": "1519",
    "boilingPoint": "2334",
    "density": "7.3",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1774",
    "period": 4,
    "group": 7,
    "displayRow": 4,
    "displayColumn": 7
  },
  {
    "atomicNumber": 26,
    "symbol": "Fe",
    "englishName": "Iron",
    "chineseName": "铁",
    "pinyin": "tiě",
    "atomicMass": "55.84",
    "electronConfiguration": "[Ar]4s2 3d6",
    "shells": [
      2,
      8,
      14,
      2
    ],
    "electronegativity": "1.83",
    "atomicRadius": "194",
    "ionizationEnergy": "7.902",
    "electronAffinity": "0.163",
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1811",
    "boilingPoint": "3134",
    "density": "7.874",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "Ancient",
    "period": 4,
    "group": 8,
    "displayRow": 4,
    "displayColumn": 8
  },
  {
    "atomicNumber": 27,
    "symbol": "Co",
    "englishName": "Cobalt",
    "chineseName": "钴",
    "pinyin": "gǔ",
    "atomicMass": "58.93319",
    "electronConfiguration": "[Ar]4s2 3d7",
    "shells": [
      2,
      8,
      15,
      2
    ],
    "electronegativity": "1.88",
    "atomicRadius": "192",
    "ionizationEnergy": "7.881",
    "electronAffinity": "0.661",
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1768",
    "boilingPoint": "3200",
    "density": "8.86",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1735",
    "period": 4,
    "group": 9,
    "displayRow": 4,
    "displayColumn": 9
  },
  {
    "atomicNumber": 28,
    "symbol": "Ni",
    "englishName": "Nickel",
    "chineseName": "镍",
    "pinyin": "niè",
    "atomicMass": "58.693",
    "electronConfiguration": "[Ar]4s2 3d8",
    "shells": [
      2,
      8,
      16,
      2
    ],
    "electronegativity": "1.91",
    "atomicRadius": "163",
    "ionizationEnergy": "7.640",
    "electronAffinity": "1.156",
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1728",
    "boilingPoint": "3186",
    "density": "8.912",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1751",
    "period": 4,
    "group": 10,
    "displayRow": 4,
    "displayColumn": 10
  },
  {
    "atomicNumber": 29,
    "symbol": "Cu",
    "englishName": "Copper",
    "chineseName": "铜",
    "pinyin": "tóng",
    "atomicMass": "63.55",
    "electronConfiguration": "[Ar]4s1 3d10",
    "shells": [
      2,
      8,
      18,
      1
    ],
    "electronegativity": "1.9",
    "atomicRadius": "140",
    "ionizationEnergy": "7.726",
    "electronAffinity": "1.228",
    "oxidationStates": "+2, +1",
    "standardState": "Solid",
    "meltingPoint": "1357.77",
    "boilingPoint": "2835",
    "density": "8.933",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "Ancient",
    "period": 4,
    "group": 11,
    "displayRow": 4,
    "displayColumn": 11
  },
  {
    "atomicNumber": 30,
    "symbol": "Zn",
    "englishName": "Zinc",
    "chineseName": "锌",
    "pinyin": "xīn",
    "atomicMass": "65.4",
    "electronConfiguration": "[Ar]4s2 3d10",
    "shells": [
      2,
      8,
      18,
      2
    ],
    "electronegativity": "1.65",
    "atomicRadius": "139",
    "ionizationEnergy": "9.394",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "692.68",
    "boilingPoint": "1180",
    "density": "7.134",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1746",
    "period": 4,
    "group": 12,
    "displayRow": 4,
    "displayColumn": 12
  },
  {
    "atomicNumber": 31,
    "symbol": "Ga",
    "englishName": "Gallium",
    "chineseName": "镓",
    "pinyin": "jiā",
    "atomicMass": "69.723",
    "electronConfiguration": "[Ar]4s2 3d10 4p1",
    "shells": [
      2,
      8,
      18,
      3
    ],
    "electronegativity": "1.81",
    "atomicRadius": "187",
    "ionizationEnergy": "5.999",
    "electronAffinity": "0.3",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "302.91",
    "boilingPoint": "2477",
    "density": "5.91",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "1875",
    "period": 4,
    "group": 13,
    "displayRow": 4,
    "displayColumn": 13
  },
  {
    "atomicNumber": 32,
    "symbol": "Ge",
    "englishName": "Germanium",
    "chineseName": "锗",
    "pinyin": "zhě",
    "atomicMass": "72.63",
    "electronConfiguration": "[Ar]4s2 3d10 4p2",
    "shells": [
      2,
      8,
      18,
      4
    ],
    "electronegativity": "2.01",
    "atomicRadius": "211",
    "ionizationEnergy": "7.900",
    "electronAffinity": "1.35",
    "oxidationStates": "+4, +2",
    "standardState": "Solid",
    "meltingPoint": "1211.4",
    "boilingPoint": "3106",
    "density": "5.323",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "1886",
    "period": 4,
    "group": 14,
    "displayRow": 4,
    "displayColumn": 14
  },
  {
    "atomicNumber": 33,
    "symbol": "As",
    "englishName": "Arsenic",
    "chineseName": "砷",
    "pinyin": "shēn",
    "atomicMass": "74.92159",
    "electronConfiguration": "[Ar]4s2 3d10 4p3",
    "shells": [
      2,
      8,
      18,
      5
    ],
    "electronegativity": "2.18",
    "atomicRadius": "185",
    "ionizationEnergy": "9.815",
    "electronAffinity": "0.81",
    "oxidationStates": "+5, +3, -3",
    "standardState": "Solid",
    "meltingPoint": "1090",
    "boilingPoint": "887",
    "density": "5.776",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "Ancient",
    "period": 4,
    "group": 15,
    "displayRow": 4,
    "displayColumn": 15
  },
  {
    "atomicNumber": 34,
    "symbol": "Se",
    "englishName": "Selenium",
    "chineseName": "硒",
    "pinyin": "xī",
    "atomicMass": "78.97",
    "electronConfiguration": "[Ar]4s2 3d10 4p4",
    "shells": [
      2,
      8,
      18,
      6
    ],
    "electronegativity": "2.55",
    "atomicRadius": "190",
    "ionizationEnergy": "9.752",
    "electronAffinity": "2.021",
    "oxidationStates": "+6, +4, -2",
    "standardState": "Solid",
    "meltingPoint": "493.65",
    "boilingPoint": "958",
    "density": "4.809",
    "category": "nonmetal",
    "categoryLabel": "非金属",
    "yearDiscovered": "1817",
    "period": 4,
    "group": 16,
    "displayRow": 4,
    "displayColumn": 16
  },
  {
    "atomicNumber": 35,
    "symbol": "Br",
    "englishName": "Bromine",
    "chineseName": "溴",
    "pinyin": "xiù",
    "atomicMass": "79.90",
    "electronConfiguration": "[Ar]4s2 3d10 4p5",
    "shells": [
      2,
      8,
      18,
      7
    ],
    "electronegativity": "2.96",
    "atomicRadius": "183",
    "ionizationEnergy": "11.814",
    "electronAffinity": "3.365",
    "oxidationStates": "+5, +1, -1",
    "standardState": "Liquid",
    "meltingPoint": "265.95",
    "boilingPoint": "331.95",
    "density": "3.11",
    "category": "halogen",
    "categoryLabel": "卤素",
    "yearDiscovered": "1826",
    "period": 4,
    "group": 17,
    "displayRow": 4,
    "displayColumn": 17
  },
  {
    "atomicNumber": 36,
    "symbol": "Kr",
    "englishName": "Krypton",
    "chineseName": "氪",
    "pinyin": "kè",
    "atomicMass": "83.80",
    "electronConfiguration": "[Ar]4s2 3d10 4p6",
    "shells": [
      2,
      8,
      18,
      8
    ],
    "electronegativity": "3",
    "atomicRadius": "202",
    "ionizationEnergy": "14.000",
    "electronAffinity": null,
    "oxidationStates": "0",
    "standardState": "Gas",
    "meltingPoint": "115.79",
    "boilingPoint": "119.93",
    "density": "0.003733",
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "1898",
    "period": 4,
    "group": 18,
    "displayRow": 4,
    "displayColumn": 18
  },
  {
    "atomicNumber": 37,
    "symbol": "Rb",
    "englishName": "Rubidium",
    "chineseName": "铷",
    "pinyin": "rú",
    "atomicMass": "85.468",
    "electronConfiguration": "[Kr]5s1",
    "shells": [
      2,
      8,
      18,
      8,
      1
    ],
    "electronegativity": "0.82",
    "atomicRadius": "303",
    "ionizationEnergy": "4.177",
    "electronAffinity": "0.468",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "312.46",
    "boilingPoint": "961",
    "density": "1.53",
    "category": "alkali-metal",
    "categoryLabel": "碱金属",
    "yearDiscovered": "1861",
    "period": 5,
    "group": 1,
    "displayRow": 5,
    "displayColumn": 1
  },
  {
    "atomicNumber": 38,
    "symbol": "Sr",
    "englishName": "Strontium",
    "chineseName": "锶",
    "pinyin": "sī",
    "atomicMass": "87.62",
    "electronConfiguration": "[Kr]5s2",
    "shells": [
      2,
      8,
      18,
      8,
      2
    ],
    "electronegativity": "0.95",
    "atomicRadius": "249",
    "ionizationEnergy": "5.695",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "1050",
    "boilingPoint": "1655",
    "density": "2.64",
    "category": "alkaline-earth",
    "categoryLabel": "碱土金属",
    "yearDiscovered": "1790",
    "period": 5,
    "group": 2,
    "displayRow": 5,
    "displayColumn": 2
  },
  {
    "atomicNumber": 39,
    "symbol": "Y",
    "englishName": "Yttrium",
    "chineseName": "钇",
    "pinyin": "yǐ",
    "atomicMass": "88.90584",
    "electronConfiguration": "[Kr]5s2 4d1",
    "shells": [
      2,
      8,
      18,
      9,
      2
    ],
    "electronegativity": "1.22",
    "atomicRadius": "219",
    "ionizationEnergy": "6.217",
    "electronAffinity": "0.307",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1795",
    "boilingPoint": "3618",
    "density": "4.47",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1794",
    "period": 5,
    "group": 3,
    "displayRow": 5,
    "displayColumn": 3
  },
  {
    "atomicNumber": 40,
    "symbol": "Zr",
    "englishName": "Zirconium",
    "chineseName": "锆",
    "pinyin": "gào",
    "atomicMass": "91.22",
    "electronConfiguration": "[Kr]5s2 4d2",
    "shells": [
      2,
      8,
      18,
      10,
      2
    ],
    "electronegativity": "1.33",
    "atomicRadius": "186",
    "ionizationEnergy": "6.634",
    "electronAffinity": "0.426",
    "oxidationStates": "+4",
    "standardState": "Solid",
    "meltingPoint": "2128",
    "boilingPoint": "4682",
    "density": "6.52",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1789",
    "period": 5,
    "group": 4,
    "displayRow": 5,
    "displayColumn": 4
  },
  {
    "atomicNumber": 41,
    "symbol": "Nb",
    "englishName": "Niobium",
    "chineseName": "铌",
    "pinyin": "ní",
    "atomicMass": "92.90637",
    "electronConfiguration": "[Kr]5s1 4d4",
    "shells": [
      2,
      8,
      18,
      12,
      1
    ],
    "electronegativity": "1.6",
    "atomicRadius": "207",
    "ionizationEnergy": "6.759",
    "electronAffinity": "0.893",
    "oxidationStates": "+5, +3",
    "standardState": "Solid",
    "meltingPoint": "2750",
    "boilingPoint": "5017",
    "density": "8.57",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1801",
    "period": 5,
    "group": 5,
    "displayRow": 5,
    "displayColumn": 5
  },
  {
    "atomicNumber": 42,
    "symbol": "Mo",
    "englishName": "Molybdenum",
    "chineseName": "钼",
    "pinyin": "mù",
    "atomicMass": "95.95",
    "electronConfiguration": "[Kr]5s1 4d5",
    "shells": [
      2,
      8,
      18,
      13,
      1
    ],
    "electronegativity": "2.16",
    "atomicRadius": "209",
    "ionizationEnergy": "7.092",
    "electronAffinity": "0.746",
    "oxidationStates": "+6",
    "standardState": "Solid",
    "meltingPoint": "2896",
    "boilingPoint": "4912",
    "density": "10.2",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1778",
    "period": 5,
    "group": 6,
    "displayRow": 5,
    "displayColumn": 6
  },
  {
    "atomicNumber": 43,
    "symbol": "Tc",
    "englishName": "Technetium",
    "chineseName": "锝",
    "pinyin": "dé",
    "atomicMass": "96.90636",
    "electronConfiguration": "[Kr]5s2 4d5",
    "shells": [
      2,
      8,
      18,
      13,
      2
    ],
    "electronegativity": "1.9",
    "atomicRadius": "209",
    "ionizationEnergy": "7.28",
    "electronAffinity": "0.55",
    "oxidationStates": "+7, +6, +4",
    "standardState": "Solid",
    "meltingPoint": "2430",
    "boilingPoint": "4538",
    "density": "11",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1937",
    "period": 5,
    "group": 7,
    "displayRow": 5,
    "displayColumn": 7
  },
  {
    "atomicNumber": 44,
    "symbol": "Ru",
    "englishName": "Ruthenium",
    "chineseName": "钌",
    "pinyin": "liǎo",
    "atomicMass": "101.1",
    "electronConfiguration": "[Kr]5s1 4d7",
    "shells": [
      2,
      8,
      18,
      15,
      1
    ],
    "electronegativity": "2.2",
    "atomicRadius": "207",
    "ionizationEnergy": "7.361",
    "electronAffinity": "1.05",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "2607",
    "boilingPoint": "4423",
    "density": "12.1",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1827",
    "period": 5,
    "group": 8,
    "displayRow": 5,
    "displayColumn": 8
  },
  {
    "atomicNumber": 45,
    "symbol": "Rh",
    "englishName": "Rhodium",
    "chineseName": "铑",
    "pinyin": "lǎo",
    "atomicMass": "102.9055",
    "electronConfiguration": "[Kr]5s1 4d8",
    "shells": [
      2,
      8,
      18,
      16,
      1
    ],
    "electronegativity": "2.28",
    "atomicRadius": "195",
    "ionizationEnergy": "7.459",
    "electronAffinity": "1.137",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "2237",
    "boilingPoint": "3968",
    "density": "12.4",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1803",
    "period": 5,
    "group": 9,
    "displayRow": 5,
    "displayColumn": 9
  },
  {
    "atomicNumber": 46,
    "symbol": "Pd",
    "englishName": "Palladium",
    "chineseName": "钯",
    "pinyin": "bǎ",
    "atomicMass": "106.42",
    "electronConfiguration": "[Kr]4d10",
    "shells": [
      2,
      8,
      18,
      18
    ],
    "electronegativity": "2.2",
    "atomicRadius": "202",
    "ionizationEnergy": "8.337",
    "electronAffinity": "0.557",
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1828.05",
    "boilingPoint": "3236",
    "density": "12.0",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1803",
    "period": 5,
    "group": 10,
    "displayRow": 5,
    "displayColumn": 10
  },
  {
    "atomicNumber": 47,
    "symbol": "Ag",
    "englishName": "Silver",
    "chineseName": "银",
    "pinyin": "yín",
    "atomicMass": "107.868",
    "electronConfiguration": "[Kr]5s1 4d10",
    "shells": [
      2,
      8,
      18,
      18,
      1
    ],
    "electronegativity": "1.93",
    "atomicRadius": "172",
    "ionizationEnergy": "7.576",
    "electronAffinity": "1.302",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "1234.93",
    "boilingPoint": "2435",
    "density": "10.501",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "Ancient",
    "period": 5,
    "group": 11,
    "displayRow": 5,
    "displayColumn": 11
  },
  {
    "atomicNumber": 48,
    "symbol": "Cd",
    "englishName": "Cadmium",
    "chineseName": "镉",
    "pinyin": "gé",
    "atomicMass": "112.41",
    "electronConfiguration": "[Kr]5s2 4d10",
    "shells": [
      2,
      8,
      18,
      18,
      2
    ],
    "electronegativity": "1.69",
    "atomicRadius": "158",
    "ionizationEnergy": "8.994",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "594.22",
    "boilingPoint": "1040",
    "density": "8.69",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1817",
    "period": 5,
    "group": 12,
    "displayRow": 5,
    "displayColumn": 12
  },
  {
    "atomicNumber": 49,
    "symbol": "In",
    "englishName": "Indium",
    "chineseName": "铟",
    "pinyin": "yīn",
    "atomicMass": "114.818",
    "electronConfiguration": "[Kr]5s2 4d10 5p1",
    "shells": [
      2,
      8,
      18,
      18,
      3
    ],
    "electronegativity": "1.78",
    "atomicRadius": "193",
    "ionizationEnergy": "5.786",
    "electronAffinity": "0.3",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "429.75",
    "boilingPoint": "2345",
    "density": "7.31",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "1863",
    "period": 5,
    "group": 13,
    "displayRow": 5,
    "displayColumn": 13
  },
  {
    "atomicNumber": 50,
    "symbol": "Sn",
    "englishName": "Tin",
    "chineseName": "锡",
    "pinyin": "xī",
    "atomicMass": "118.71",
    "electronConfiguration": "[Kr]5s2 4d10 5p2",
    "shells": [
      2,
      8,
      18,
      18,
      4
    ],
    "electronegativity": "1.96",
    "atomicRadius": "217",
    "ionizationEnergy": "7.344",
    "electronAffinity": "1.2",
    "oxidationStates": "+4, +2",
    "standardState": "Solid",
    "meltingPoint": "505.08",
    "boilingPoint": "2875",
    "density": "7.287",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "Ancient",
    "period": 5,
    "group": 14,
    "displayRow": 5,
    "displayColumn": 14
  },
  {
    "atomicNumber": 51,
    "symbol": "Sb",
    "englishName": "Antimony",
    "chineseName": "锑",
    "pinyin": "tī",
    "atomicMass": "121.760",
    "electronConfiguration": "[Kr]5s2 4d10 5p3",
    "shells": [
      2,
      8,
      18,
      18,
      5
    ],
    "electronegativity": "2.05",
    "atomicRadius": "206",
    "ionizationEnergy": "8.64",
    "electronAffinity": "1.07",
    "oxidationStates": "+5, +3, -3",
    "standardState": "Solid",
    "meltingPoint": "903.78",
    "boilingPoint": "1860",
    "density": "6.685",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "Ancient",
    "period": 5,
    "group": 15,
    "displayRow": 5,
    "displayColumn": 15
  },
  {
    "atomicNumber": 52,
    "symbol": "Te",
    "englishName": "Tellurium",
    "chineseName": "碲",
    "pinyin": "dì",
    "atomicMass": "127.6",
    "electronConfiguration": "[Kr]5s2 4d10 5p4",
    "shells": [
      2,
      8,
      18,
      18,
      6
    ],
    "electronegativity": "2.1",
    "atomicRadius": "206",
    "ionizationEnergy": "9.010",
    "electronAffinity": "1.971",
    "oxidationStates": "+6, +4, -2",
    "standardState": "Solid",
    "meltingPoint": "722.66",
    "boilingPoint": "1261",
    "density": "6.232",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "1782",
    "period": 5,
    "group": 16,
    "displayRow": 5,
    "displayColumn": 16
  },
  {
    "atomicNumber": 53,
    "symbol": "I",
    "englishName": "Iodine",
    "chineseName": "碘",
    "pinyin": "diǎn",
    "atomicMass": "126.9045",
    "electronConfiguration": "[Kr]5s2 4d10 5p5",
    "shells": [
      2,
      8,
      18,
      18,
      7
    ],
    "electronegativity": "2.66",
    "atomicRadius": "198",
    "ionizationEnergy": "10.451",
    "electronAffinity": "3.059",
    "oxidationStates": "+7, +5, +1, -1",
    "standardState": "Solid",
    "meltingPoint": "386.85",
    "boilingPoint": "457.55",
    "density": "4.93",
    "category": "halogen",
    "categoryLabel": "卤素",
    "yearDiscovered": "1811",
    "period": 5,
    "group": 17,
    "displayRow": 5,
    "displayColumn": 17
  },
  {
    "atomicNumber": 54,
    "symbol": "Xe",
    "englishName": "Xenon",
    "chineseName": "氙",
    "pinyin": "xiān",
    "atomicMass": "131.29",
    "electronConfiguration": "[Kr]5s2 4d10 5p6",
    "shells": [
      2,
      8,
      18,
      18,
      8
    ],
    "electronegativity": "2.6",
    "atomicRadius": "216",
    "ionizationEnergy": "12.130",
    "electronAffinity": null,
    "oxidationStates": "0",
    "standardState": "Gas",
    "meltingPoint": "161.36",
    "boilingPoint": "165.03",
    "density": "0.005887",
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "1898",
    "period": 5,
    "group": 18,
    "displayRow": 5,
    "displayColumn": 18
  },
  {
    "atomicNumber": 55,
    "symbol": "Cs",
    "englishName": "Cesium",
    "chineseName": "铯",
    "pinyin": "sè",
    "atomicMass": "132.9054520",
    "electronConfiguration": "[Xe]6s1",
    "shells": [
      2,
      8,
      18,
      18,
      8,
      1
    ],
    "electronegativity": "0.79",
    "atomicRadius": "343",
    "ionizationEnergy": "3.894",
    "electronAffinity": "0.472",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "301.59",
    "boilingPoint": "944",
    "density": "1.93",
    "category": "alkali-metal",
    "categoryLabel": "碱金属",
    "yearDiscovered": "1860",
    "period": 6,
    "group": 1,
    "displayRow": 6,
    "displayColumn": 1
  },
  {
    "atomicNumber": 56,
    "symbol": "Ba",
    "englishName": "Barium",
    "chineseName": "钡",
    "pinyin": "bèi",
    "atomicMass": "137.33",
    "electronConfiguration": "[Xe]6s2",
    "shells": [
      2,
      8,
      18,
      18,
      8,
      2
    ],
    "electronegativity": "0.89",
    "atomicRadius": "268",
    "ionizationEnergy": "5.212",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "1000",
    "boilingPoint": "2170",
    "density": "3.62",
    "category": "alkaline-earth",
    "categoryLabel": "碱土金属",
    "yearDiscovered": "1808",
    "period": 6,
    "group": 2,
    "displayRow": 6,
    "displayColumn": 2
  },
  {
    "atomicNumber": 57,
    "symbol": "La",
    "englishName": "Lanthanum",
    "chineseName": "镧",
    "pinyin": "lán",
    "atomicMass": "138.9055",
    "electronConfiguration": "[Xe]6s2 5d1",
    "shells": [
      2,
      8,
      18,
      18,
      9,
      2
    ],
    "electronegativity": "1.1",
    "atomicRadius": "240",
    "ionizationEnergy": "5.577",
    "electronAffinity": "0.5",
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1191",
    "boilingPoint": "3737",
    "density": "6.15",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1839",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 3
  },
  {
    "atomicNumber": 58,
    "symbol": "Ce",
    "englishName": "Cerium",
    "chineseName": "铈",
    "pinyin": "shì",
    "atomicMass": "140.116",
    "electronConfiguration": "[Xe]6s2 4f1 5d1",
    "shells": [
      2,
      8,
      18,
      19,
      9,
      2
    ],
    "electronegativity": "1.12",
    "atomicRadius": "235",
    "ionizationEnergy": "5.539",
    "electronAffinity": "0.5",
    "oxidationStates": "+4, +3",
    "standardState": "Solid",
    "meltingPoint": "1071",
    "boilingPoint": "3697",
    "density": "6.770",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1803",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 4
  },
  {
    "atomicNumber": 59,
    "symbol": "Pr",
    "englishName": "Praseodymium",
    "chineseName": "镨",
    "pinyin": "pǔ",
    "atomicMass": "140.90766",
    "electronConfiguration": "[Xe]6s2 4f3",
    "shells": [
      2,
      8,
      18,
      21,
      8,
      2
    ],
    "electronegativity": "1.13",
    "atomicRadius": "239",
    "ionizationEnergy": "5.464",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1204",
    "boilingPoint": "3793",
    "density": "6.77",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1885",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 5
  },
  {
    "atomicNumber": 60,
    "symbol": "Nd",
    "englishName": "Neodymium",
    "chineseName": "钕",
    "pinyin": "nǚ",
    "atomicMass": "144.24",
    "electronConfiguration": "[Xe]6s2 4f4",
    "shells": [
      2,
      8,
      18,
      22,
      8,
      2
    ],
    "electronegativity": "1.14",
    "atomicRadius": "229",
    "ionizationEnergy": "5.525",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1294",
    "boilingPoint": "3347",
    "density": "7.01",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1885",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 6
  },
  {
    "atomicNumber": 61,
    "symbol": "Pm",
    "englishName": "Promethium",
    "chineseName": "钷",
    "pinyin": "pǒ",
    "atomicMass": "144.91276",
    "electronConfiguration": "[Xe]6s2 4f5",
    "shells": [
      2,
      8,
      18,
      23,
      8,
      2
    ],
    "electronegativity": null,
    "atomicRadius": "236",
    "ionizationEnergy": "5.55",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1315",
    "boilingPoint": "3273",
    "density": "7.26",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1945",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 7
  },
  {
    "atomicNumber": 62,
    "symbol": "Sm",
    "englishName": "Samarium",
    "chineseName": "钐",
    "pinyin": "shān",
    "atomicMass": "150.4",
    "electronConfiguration": "[Xe]6s2 4f6",
    "shells": [
      2,
      8,
      18,
      24,
      8,
      2
    ],
    "electronegativity": "1.17",
    "atomicRadius": "229",
    "ionizationEnergy": "5.644",
    "electronAffinity": null,
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1347",
    "boilingPoint": "2067",
    "density": "7.52",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1879",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 8
  },
  {
    "atomicNumber": 63,
    "symbol": "Eu",
    "englishName": "Europium",
    "chineseName": "铕",
    "pinyin": "yǒu",
    "atomicMass": "151.964",
    "electronConfiguration": "[Xe]6s2 4f7",
    "shells": [
      2,
      8,
      18,
      25,
      8,
      2
    ],
    "electronegativity": null,
    "atomicRadius": "233",
    "ionizationEnergy": "5.670",
    "electronAffinity": null,
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1095",
    "boilingPoint": "1802",
    "density": "5.24",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1901",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 9
  },
  {
    "atomicNumber": 64,
    "symbol": "Gd",
    "englishName": "Gadolinium",
    "chineseName": "钆",
    "pinyin": "gá",
    "atomicMass": "157.25",
    "electronConfiguration": "[Xe]6s2 4f7 5d1",
    "shells": [
      2,
      8,
      18,
      25,
      9,
      2
    ],
    "electronegativity": "1.2",
    "atomicRadius": "237",
    "ionizationEnergy": "6.150",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1586",
    "boilingPoint": "3546",
    "density": "7.90",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1880",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 10
  },
  {
    "atomicNumber": 65,
    "symbol": "Tb",
    "englishName": "Terbium",
    "chineseName": "铽",
    "pinyin": "tè",
    "atomicMass": "158.92535",
    "electronConfiguration": "[Xe]6s2 4f9",
    "shells": [
      2,
      8,
      18,
      27,
      8,
      2
    ],
    "electronegativity": null,
    "atomicRadius": "221",
    "ionizationEnergy": "5.864",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1629",
    "boilingPoint": "3503",
    "density": "8.23",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1843",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 11
  },
  {
    "atomicNumber": 66,
    "symbol": "Dy",
    "englishName": "Dysprosium",
    "chineseName": "镝",
    "pinyin": "dī",
    "atomicMass": "162.500",
    "electronConfiguration": "[Xe]6s2 4f10",
    "shells": [
      2,
      8,
      18,
      28,
      8,
      2
    ],
    "electronegativity": "1.22",
    "atomicRadius": "229",
    "ionizationEnergy": "5.939",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1685",
    "boilingPoint": "2840",
    "density": "8.55",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1886",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 12
  },
  {
    "atomicNumber": 67,
    "symbol": "Ho",
    "englishName": "Holmium",
    "chineseName": "钬",
    "pinyin": "huǒ",
    "atomicMass": "164.93033",
    "electronConfiguration": "[Xe]6s2 4f11",
    "shells": [
      2,
      8,
      18,
      29,
      8,
      2
    ],
    "electronegativity": "1.23",
    "atomicRadius": "216",
    "ionizationEnergy": "6.022",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1747",
    "boilingPoint": "2973",
    "density": "8.80",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1878",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 13
  },
  {
    "atomicNumber": 68,
    "symbol": "Er",
    "englishName": "Erbium",
    "chineseName": "铒",
    "pinyin": "ěr",
    "atomicMass": "167.26",
    "electronConfiguration": "[Xe]6s2 4f12",
    "shells": [
      2,
      8,
      18,
      30,
      8,
      2
    ],
    "electronegativity": "1.24",
    "atomicRadius": "235",
    "ionizationEnergy": "6.108",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1802",
    "boilingPoint": "3141",
    "density": "9.07",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1843",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 14
  },
  {
    "atomicNumber": 69,
    "symbol": "Tm",
    "englishName": "Thulium",
    "chineseName": "铥",
    "pinyin": "diū",
    "atomicMass": "168.93422",
    "electronConfiguration": "[Xe]6s2 4f13",
    "shells": [
      2,
      8,
      18,
      31,
      8,
      2
    ],
    "electronegativity": "1.25",
    "atomicRadius": "227",
    "ionizationEnergy": "6.184",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1818",
    "boilingPoint": "2223",
    "density": "9.32",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1879",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 15
  },
  {
    "atomicNumber": 70,
    "symbol": "Yb",
    "englishName": "Ytterbium",
    "chineseName": "镱",
    "pinyin": "yì",
    "atomicMass": "173.05",
    "electronConfiguration": "[Xe]6s2 4f14",
    "shells": [
      2,
      8,
      18,
      32,
      8,
      2
    ],
    "electronegativity": null,
    "atomicRadius": "242",
    "ionizationEnergy": "6.254",
    "electronAffinity": null,
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1092",
    "boilingPoint": "1469",
    "density": "6.90",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1878",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 16
  },
  {
    "atomicNumber": 71,
    "symbol": "Lu",
    "englishName": "Lutetium",
    "chineseName": "镥",
    "pinyin": "lǔ",
    "atomicMass": "174.9667",
    "electronConfiguration": "[Xe]6s2 4f14 5d1",
    "shells": [
      2,
      8,
      18,
      32,
      9,
      2
    ],
    "electronegativity": "1.27",
    "atomicRadius": "221",
    "ionizationEnergy": "5.426",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1936",
    "boilingPoint": "3675",
    "density": "9.84",
    "category": "lanthanide",
    "categoryLabel": "镧系元素",
    "yearDiscovered": "1907",
    "period": 6,
    "group": null,
    "displayRow": 8,
    "displayColumn": 17
  },
  {
    "atomicNumber": 72,
    "symbol": "Hf",
    "englishName": "Hafnium",
    "chineseName": "铪",
    "pinyin": "hā",
    "atomicMass": "178.49",
    "electronConfiguration": "[Xe]6s2 4f14 5d2",
    "shells": [
      2,
      8,
      18,
      32,
      10,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "212",
    "ionizationEnergy": "6.825",
    "electronAffinity": null,
    "oxidationStates": "+4",
    "standardState": "Solid",
    "meltingPoint": "2506",
    "boilingPoint": "4876",
    "density": "13.3",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1923",
    "period": 6,
    "group": 4,
    "displayRow": 6,
    "displayColumn": 4
  },
  {
    "atomicNumber": 73,
    "symbol": "Ta",
    "englishName": "Tantalum",
    "chineseName": "钽",
    "pinyin": "tǎn",
    "atomicMass": "180.9479",
    "electronConfiguration": "[Xe]6s2 4f14 5d3",
    "shells": [
      2,
      8,
      18,
      32,
      11,
      2
    ],
    "electronegativity": "1.5",
    "atomicRadius": "217",
    "ionizationEnergy": "7.89",
    "electronAffinity": "0.322",
    "oxidationStates": "+5",
    "standardState": "Solid",
    "meltingPoint": "3290",
    "boilingPoint": "5731",
    "density": "16.4",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1802",
    "period": 6,
    "group": 5,
    "displayRow": 6,
    "displayColumn": 5
  },
  {
    "atomicNumber": 74,
    "symbol": "W",
    "englishName": "Tungsten",
    "chineseName": "钨",
    "pinyin": "wū",
    "atomicMass": "183.84",
    "electronConfiguration": "[Xe]6s2 4f14 5d4",
    "shells": [
      2,
      8,
      18,
      32,
      12,
      2
    ],
    "electronegativity": "2.36",
    "atomicRadius": "210",
    "ionizationEnergy": "7.98",
    "electronAffinity": "0.815",
    "oxidationStates": "+6",
    "standardState": "Solid",
    "meltingPoint": "3695",
    "boilingPoint": "5828",
    "density": "19.3",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1783",
    "period": 6,
    "group": 6,
    "displayRow": 6,
    "displayColumn": 6
  },
  {
    "atomicNumber": 75,
    "symbol": "Re",
    "englishName": "Rhenium",
    "chineseName": "铼",
    "pinyin": "lái",
    "atomicMass": "186.207",
    "electronConfiguration": "[Xe]6s2 4f14 5d5",
    "shells": [
      2,
      8,
      18,
      32,
      13,
      2
    ],
    "electronegativity": "1.9",
    "atomicRadius": "217",
    "ionizationEnergy": "7.88",
    "electronAffinity": "0.15",
    "oxidationStates": "+7, +6, +4",
    "standardState": "Solid",
    "meltingPoint": "3459",
    "boilingPoint": "5869",
    "density": "20.8",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1925",
    "period": 6,
    "group": 7,
    "displayRow": 6,
    "displayColumn": 7
  },
  {
    "atomicNumber": 76,
    "symbol": "Os",
    "englishName": "Osmium",
    "chineseName": "锇",
    "pinyin": "é",
    "atomicMass": "190.2",
    "electronConfiguration": "[Xe]6s2 4f14 5d6",
    "shells": [
      2,
      8,
      18,
      32,
      14,
      2
    ],
    "electronegativity": "2.2",
    "atomicRadius": "216",
    "ionizationEnergy": "8.7",
    "electronAffinity": "1.1",
    "oxidationStates": "+4, +3",
    "standardState": "Solid",
    "meltingPoint": "3306",
    "boilingPoint": "5285",
    "density": "22.57",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1803",
    "period": 6,
    "group": 8,
    "displayRow": 6,
    "displayColumn": 8
  },
  {
    "atomicNumber": 77,
    "symbol": "Ir",
    "englishName": "Iridium",
    "chineseName": "铱",
    "pinyin": "yī",
    "atomicMass": "192.22",
    "electronConfiguration": "[Xe]6s2 4f14 5d7",
    "shells": [
      2,
      8,
      18,
      32,
      15,
      2
    ],
    "electronegativity": "2.2",
    "atomicRadius": "202",
    "ionizationEnergy": "9.1",
    "electronAffinity": "1.565",
    "oxidationStates": "+4, +3",
    "standardState": "Solid",
    "meltingPoint": "2719",
    "boilingPoint": "4701",
    "density": "22.42",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1803",
    "period": 6,
    "group": 9,
    "displayRow": 6,
    "displayColumn": 9
  },
  {
    "atomicNumber": 78,
    "symbol": "Pt",
    "englishName": "Platinum",
    "chineseName": "铂",
    "pinyin": "bó",
    "atomicMass": "195.08",
    "electronConfiguration": "[Xe]6s1 4f14 5d9",
    "shells": [
      2,
      8,
      18,
      32,
      17,
      1
    ],
    "electronegativity": "2.28",
    "atomicRadius": "209",
    "ionizationEnergy": "9",
    "electronAffinity": "2.128",
    "oxidationStates": "+4, +2",
    "standardState": "Solid",
    "meltingPoint": "2041.55",
    "boilingPoint": "4098",
    "density": "21.46",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1735",
    "period": 6,
    "group": 10,
    "displayRow": 6,
    "displayColumn": 10
  },
  {
    "atomicNumber": 79,
    "symbol": "Au",
    "englishName": "Gold",
    "chineseName": "金",
    "pinyin": "jīn",
    "atomicMass": "196.96657",
    "electronConfiguration": "[Xe]6s1 4f14 5d10",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      1
    ],
    "electronegativity": "2.54",
    "atomicRadius": "166",
    "ionizationEnergy": "9.226",
    "electronAffinity": "2.309",
    "oxidationStates": "+3, +1",
    "standardState": "Solid",
    "meltingPoint": "1337.33",
    "boilingPoint": "3129",
    "density": "19.282",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "Ancient",
    "period": 6,
    "group": 11,
    "displayRow": 6,
    "displayColumn": 11
  },
  {
    "atomicNumber": 80,
    "symbol": "Hg",
    "englishName": "Mercury",
    "chineseName": "汞",
    "pinyin": "gǒng",
    "atomicMass": "200.59",
    "electronConfiguration": "[Xe]6s2 4f14 5d10",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      2
    ],
    "electronegativity": "2",
    "atomicRadius": "209",
    "ionizationEnergy": "10.438",
    "electronAffinity": null,
    "oxidationStates": "+2, +1",
    "standardState": "Liquid",
    "meltingPoint": "234.32",
    "boilingPoint": "629.88",
    "density": "13.5336",
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "Ancient",
    "period": 6,
    "group": 12,
    "displayRow": 6,
    "displayColumn": 12
  },
  {
    "atomicNumber": 81,
    "symbol": "Tl",
    "englishName": "Thallium",
    "chineseName": "铊",
    "pinyin": "tā",
    "atomicMass": "204.383",
    "electronConfiguration": "[Xe]6s2 4f14 5d10 6p1",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      3
    ],
    "electronegativity": "1.62",
    "atomicRadius": "196",
    "ionizationEnergy": "6.108",
    "electronAffinity": "0.2",
    "oxidationStates": "+3, +1",
    "standardState": "Solid",
    "meltingPoint": "577",
    "boilingPoint": "1746",
    "density": "11.8",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "1861",
    "period": 6,
    "group": 13,
    "displayRow": 6,
    "displayColumn": 13
  },
  {
    "atomicNumber": 82,
    "symbol": "Pb",
    "englishName": "Lead",
    "chineseName": "铅",
    "pinyin": "qiān",
    "atomicMass": "207",
    "electronConfiguration": "[Xe]6s2 4f14 5d10 6p2",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      4
    ],
    "electronegativity": "2.33",
    "atomicRadius": "202",
    "ionizationEnergy": "7.417",
    "electronAffinity": "0.36",
    "oxidationStates": "+4, +2",
    "standardState": "Solid",
    "meltingPoint": "600.61",
    "boilingPoint": "2022",
    "density": "11.342",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "Ancient",
    "period": 6,
    "group": 14,
    "displayRow": 6,
    "displayColumn": 14
  },
  {
    "atomicNumber": 83,
    "symbol": "Bi",
    "englishName": "Bismuth",
    "chineseName": "铋",
    "pinyin": "bì",
    "atomicMass": "208.98040",
    "electronConfiguration": "[Xe]6s2 4f14 5d10 6p3",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      5
    ],
    "electronegativity": "2.02",
    "atomicRadius": "207",
    "ionizationEnergy": "7.289",
    "electronAffinity": "0.946",
    "oxidationStates": "+5, +3",
    "standardState": "Solid",
    "meltingPoint": "544.55",
    "boilingPoint": "1837",
    "density": "9.807",
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "1753",
    "period": 6,
    "group": 15,
    "displayRow": 6,
    "displayColumn": 15
  },
  {
    "atomicNumber": 84,
    "symbol": "Po",
    "englishName": "Polonium",
    "chineseName": "钋",
    "pinyin": "pō",
    "atomicMass": "208.98243",
    "electronConfiguration": "[Xe]6s2 4f14 5d10 6p4",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      6
    ],
    "electronegativity": "2",
    "atomicRadius": "197",
    "ionizationEnergy": "8.417",
    "electronAffinity": "1.9",
    "oxidationStates": "+4, +2",
    "standardState": "Solid",
    "meltingPoint": "527",
    "boilingPoint": "1235",
    "density": "9.32",
    "category": "metalloid",
    "categoryLabel": "类金属",
    "yearDiscovered": "1898",
    "period": 6,
    "group": 16,
    "displayRow": 6,
    "displayColumn": 16
  },
  {
    "atomicNumber": 85,
    "symbol": "At",
    "englishName": "Astatine",
    "chineseName": "砹",
    "pinyin": "ài",
    "atomicMass": "209.98715",
    "electronConfiguration": "[Xe]6s2 4f14 5d10 6p5",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      7
    ],
    "electronegativity": "2.2",
    "atomicRadius": "202",
    "ionizationEnergy": "9.5",
    "electronAffinity": "2.8",
    "oxidationStates": "7, 5, 3, 1, -1",
    "standardState": "Solid",
    "meltingPoint": "575",
    "boilingPoint": null,
    "density": "7",
    "category": "halogen",
    "categoryLabel": "卤素",
    "yearDiscovered": "1940",
    "period": 6,
    "group": 17,
    "displayRow": 6,
    "displayColumn": 17
  },
  {
    "atomicNumber": 86,
    "symbol": "Rn",
    "englishName": "Radon",
    "chineseName": "氡",
    "pinyin": "dōng",
    "atomicMass": "222.01758",
    "electronConfiguration": "[Xe]6s2 4f14 5d10 6p6",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8
    ],
    "electronegativity": null,
    "atomicRadius": "220",
    "ionizationEnergy": "10.745",
    "electronAffinity": null,
    "oxidationStates": "0",
    "standardState": "Gas",
    "meltingPoint": "202",
    "boilingPoint": "211.45",
    "density": "0.00973",
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "1900",
    "period": 6,
    "group": 18,
    "displayRow": 6,
    "displayColumn": 18
  },
  {
    "atomicNumber": 87,
    "symbol": "Fr",
    "englishName": "Francium",
    "chineseName": "钫",
    "pinyin": "fāng",
    "atomicMass": "223.01973",
    "electronConfiguration": "[Rn]7s1",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8,
      1
    ],
    "electronegativity": "0.7",
    "atomicRadius": "348",
    "ionizationEnergy": "3.9",
    "electronAffinity": "0.47",
    "oxidationStates": "+1",
    "standardState": "Solid",
    "meltingPoint": "300",
    "boilingPoint": null,
    "density": null,
    "category": "alkali-metal",
    "categoryLabel": "碱金属",
    "yearDiscovered": "1939",
    "period": 7,
    "group": 1,
    "displayRow": 7,
    "displayColumn": 1
  },
  {
    "atomicNumber": 88,
    "symbol": "Ra",
    "englishName": "Radium",
    "chineseName": "镭",
    "pinyin": "léi",
    "atomicMass": "226.02541",
    "electronConfiguration": "[Rn]7s2",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8,
      2
    ],
    "electronegativity": "0.9",
    "atomicRadius": "283",
    "ionizationEnergy": "5.279",
    "electronAffinity": null,
    "oxidationStates": "+2",
    "standardState": "Solid",
    "meltingPoint": "973",
    "boilingPoint": "1413",
    "density": "5",
    "category": "alkaline-earth",
    "categoryLabel": "碱土金属",
    "yearDiscovered": "1898",
    "period": 7,
    "group": 2,
    "displayRow": 7,
    "displayColumn": 2
  },
  {
    "atomicNumber": 89,
    "symbol": "Ac",
    "englishName": "Actinium",
    "chineseName": "锕",
    "pinyin": "ā",
    "atomicMass": "227.02775",
    "electronConfiguration": "[Rn]7s2 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      9,
      2
    ],
    "electronegativity": "1.1",
    "atomicRadius": "260",
    "ionizationEnergy": "5.17",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1324",
    "boilingPoint": "3471",
    "density": "10.07",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1899",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 3
  },
  {
    "atomicNumber": 90,
    "symbol": "Th",
    "englishName": "Thorium",
    "chineseName": "钍",
    "pinyin": "tǔ",
    "atomicMass": "232.038",
    "electronConfiguration": "[Rn]7s2 6d2",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      10,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "237",
    "ionizationEnergy": "6.08",
    "electronAffinity": null,
    "oxidationStates": "+4",
    "standardState": "Solid",
    "meltingPoint": "2023",
    "boilingPoint": "5061",
    "density": "11.72",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1828",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 4
  },
  {
    "atomicNumber": 91,
    "symbol": "Pa",
    "englishName": "Protactinium",
    "chineseName": "镤",
    "pinyin": "pú",
    "atomicMass": "231.03588",
    "electronConfiguration": "[Rn]7s2 5f2 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      20,
      9,
      2
    ],
    "electronegativity": "1.5",
    "atomicRadius": "243",
    "ionizationEnergy": "5.89",
    "electronAffinity": null,
    "oxidationStates": "+5, +4",
    "standardState": "Solid",
    "meltingPoint": "1845",
    "boilingPoint": null,
    "density": "15.37",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1913",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 5
  },
  {
    "atomicNumber": 92,
    "symbol": "U",
    "englishName": "Uranium",
    "chineseName": "铀",
    "pinyin": "yóu",
    "atomicMass": "238.0289",
    "electronConfiguration": "[Rn]7s2 5f3 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      21,
      9,
      2
    ],
    "electronegativity": "1.38",
    "atomicRadius": "240",
    "ionizationEnergy": "6.194",
    "electronAffinity": null,
    "oxidationStates": "+6, +5, +4, +3",
    "standardState": "Solid",
    "meltingPoint": "1408",
    "boilingPoint": "4404",
    "density": "18.95",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1789",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 6
  },
  {
    "atomicNumber": 93,
    "symbol": "Np",
    "englishName": "Neptunium",
    "chineseName": "镎",
    "pinyin": "ná",
    "atomicMass": "237.048172",
    "electronConfiguration": "[Rn]7s2 5f4 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      22,
      9,
      2
    ],
    "electronegativity": "1.36",
    "atomicRadius": "221",
    "ionizationEnergy": "6.266",
    "electronAffinity": null,
    "oxidationStates": "+6, +5, +4, +3",
    "standardState": "Solid",
    "meltingPoint": "917",
    "boilingPoint": "4175",
    "density": "20.25",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1940",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 7
  },
  {
    "atomicNumber": 94,
    "symbol": "Pu",
    "englishName": "Plutonium",
    "chineseName": "钚",
    "pinyin": "bù",
    "atomicMass": "244.06420",
    "electronConfiguration": "[Rn]7s2 5f6",
    "shells": [
      2,
      8,
      18,
      32,
      24,
      8,
      2
    ],
    "electronegativity": "1.28",
    "atomicRadius": "243",
    "ionizationEnergy": "6.06",
    "electronAffinity": null,
    "oxidationStates": "+6, +5, +4, +3",
    "standardState": "Solid",
    "meltingPoint": "913",
    "boilingPoint": "3501",
    "density": "19.84",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1940",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 8
  },
  {
    "atomicNumber": 95,
    "symbol": "Am",
    "englishName": "Americium",
    "chineseName": "镅",
    "pinyin": "méi",
    "atomicMass": "243.061380",
    "electronConfiguration": "[Rn]7s2 5f7",
    "shells": [
      2,
      8,
      18,
      32,
      25,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "244",
    "ionizationEnergy": "5.993",
    "electronAffinity": null,
    "oxidationStates": "+6, +5, +4, +3",
    "standardState": "Solid",
    "meltingPoint": "1449",
    "boilingPoint": "2284",
    "density": "13.69",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1944",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 9
  },
  {
    "atomicNumber": 96,
    "symbol": "Cm",
    "englishName": "Curium",
    "chineseName": "锔",
    "pinyin": "jú",
    "atomicMass": "247.07035",
    "electronConfiguration": "[Rn]7s2 5f7 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      25,
      9,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "245",
    "ionizationEnergy": "6.02",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1618",
    "boilingPoint": "3400",
    "density": "13.51",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1944",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 10
  },
  {
    "atomicNumber": 97,
    "symbol": "Bk",
    "englishName": "Berkelium",
    "chineseName": "锫",
    "pinyin": "péi",
    "atomicMass": "247.07031",
    "electronConfiguration": "[Rn]7s2 5f9",
    "shells": [
      2,
      8,
      18,
      32,
      27,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "244",
    "ionizationEnergy": "6.23",
    "electronAffinity": null,
    "oxidationStates": "+4, +3",
    "standardState": "Solid",
    "meltingPoint": "1323",
    "boilingPoint": null,
    "density": "14",
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1949",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 11
  },
  {
    "atomicNumber": 98,
    "symbol": "Cf",
    "englishName": "Californium",
    "chineseName": "锎",
    "pinyin": "kāi",
    "atomicMass": "251.07959",
    "electronConfiguration": "[Rn]7s2 5f10",
    "shells": [
      2,
      8,
      18,
      32,
      28,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "245",
    "ionizationEnergy": "6.30",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1173",
    "boilingPoint": null,
    "density": null,
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1950",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 12
  },
  {
    "atomicNumber": 99,
    "symbol": "Es",
    "englishName": "Einsteinium",
    "chineseName": "锿",
    "pinyin": "āi",
    "atomicMass": "252.0830",
    "electronConfiguration": "[Rn]7s2 5f11",
    "shells": [
      2,
      8,
      18,
      32,
      29,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": "245",
    "ionizationEnergy": "6.42",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1133",
    "boilingPoint": null,
    "density": null,
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1952",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 13
  },
  {
    "atomicNumber": 100,
    "symbol": "Fm",
    "englishName": "Fermium",
    "chineseName": "镄",
    "pinyin": "fèi",
    "atomicMass": "257.09511",
    "electronConfiguration": "[Rn] 5f12 7s2",
    "shells": [
      2,
      8,
      18,
      32,
      30,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": null,
    "ionizationEnergy": "6.50",
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1800",
    "boilingPoint": null,
    "density": null,
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1952",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 14
  },
  {
    "atomicNumber": 101,
    "symbol": "Md",
    "englishName": "Mendelevium",
    "chineseName": "钔",
    "pinyin": "mén",
    "atomicMass": "258.09843",
    "electronConfiguration": "[Rn]7s2 5f13",
    "shells": [
      2,
      8,
      18,
      32,
      31,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": null,
    "ionizationEnergy": "6.58",
    "electronAffinity": null,
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1100",
    "boilingPoint": null,
    "density": null,
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1955",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 15
  },
  {
    "atomicNumber": 102,
    "symbol": "No",
    "englishName": "Nobelium",
    "chineseName": "锘",
    "pinyin": "nuò",
    "atomicMass": "259.10100",
    "electronConfiguration": "[Rn]7s2 5f14",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      8,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": null,
    "ionizationEnergy": "6.65",
    "electronAffinity": null,
    "oxidationStates": "+3, +2",
    "standardState": "Solid",
    "meltingPoint": "1100",
    "boilingPoint": null,
    "density": null,
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1957",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 16
  },
  {
    "atomicNumber": 103,
    "symbol": "Lr",
    "englishName": "Lawrencium",
    "chineseName": "铹",
    "pinyin": "láo",
    "atomicMass": "266.120",
    "electronConfiguration": "[Rn]7s2 5f14 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      9,
      2
    ],
    "electronegativity": "1.3",
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "+3",
    "standardState": "Solid",
    "meltingPoint": "1900",
    "boilingPoint": null,
    "density": null,
    "category": "actinide",
    "categoryLabel": "锕系元素",
    "yearDiscovered": "1961",
    "period": 7,
    "group": null,
    "displayRow": 9,
    "displayColumn": 17
  },
  {
    "atomicNumber": 104,
    "symbol": "Rf",
    "englishName": "Rutherfordium",
    "chineseName": "𬬻",
    "pinyin": "lú",
    "atomicMass": "267.122",
    "electronConfiguration": "[Rn]7s2 5f14 6d2",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      10,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "+4",
    "standardState": "Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1964",
    "period": 7,
    "group": 4,
    "displayRow": 7,
    "displayColumn": 4
  },
  {
    "atomicNumber": 105,
    "symbol": "Db",
    "englishName": "Dubnium",
    "chineseName": "𬭊",
    "pinyin": "dù",
    "atomicMass": "268.126",
    "electronConfiguration": "[Rn]7s2 5f14 6d3",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      11,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "5, 4, 3",
    "standardState": "Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1967",
    "period": 7,
    "group": 5,
    "displayRow": 7,
    "displayColumn": 5
  },
  {
    "atomicNumber": 106,
    "symbol": "Sg",
    "englishName": "Seaborgium",
    "chineseName": "𬭳",
    "pinyin": "xǐ",
    "atomicMass": "269.128",
    "electronConfiguration": "[Rn]7s2 5f14 6d4",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      12,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "6, 5, 4, 3, 0",
    "standardState": "Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1974",
    "period": 7,
    "group": 6,
    "displayRow": 7,
    "displayColumn": 6
  },
  {
    "atomicNumber": 107,
    "symbol": "Bh",
    "englishName": "Bohrium",
    "chineseName": "𬭛",
    "pinyin": "bō",
    "atomicMass": "270.133",
    "electronConfiguration": "[Rn]7s2 5f14 6d5",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      13,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "7, 5, 4, 3",
    "standardState": "Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1976",
    "period": 7,
    "group": 7,
    "displayRow": 7,
    "displayColumn": 7
  },
  {
    "atomicNumber": 108,
    "symbol": "Hs",
    "englishName": "Hassium",
    "chineseName": "𬭶",
    "pinyin": "hēi",
    "atomicMass": "269.1336",
    "electronConfiguration": "[Rn]7s2 5f14 6d6",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      14,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "8, 6, 5, 4, 3, 2",
    "standardState": "Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1984",
    "period": 7,
    "group": 8,
    "displayRow": 7,
    "displayColumn": 8
  },
  {
    "atomicNumber": 109,
    "symbol": "Mt",
    "englishName": "Meitnerium",
    "chineseName": "鿏",
    "pinyin": "mài",
    "atomicMass": "277.154",
    "electronConfiguration": "[Rn]7s2 5f14 6d7 (calculated)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      15,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "9, 8, 6, 4, 3, 1",
    "standardState": "Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1982",
    "period": 7,
    "group": 9,
    "displayRow": 7,
    "displayColumn": 9
  },
  {
    "atomicNumber": 110,
    "symbol": "Ds",
    "englishName": "Darmstadtium",
    "chineseName": "𫟼",
    "pinyin": "dá",
    "atomicMass": "282.166",
    "electronConfiguration": "[Rn]7s2 5f14 6d8 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      16,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "8, 6, 4, 2, 0",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1994",
    "period": 7,
    "group": 10,
    "displayRow": 7,
    "displayColumn": 10
  },
  {
    "atomicNumber": 111,
    "symbol": "Rg",
    "englishName": "Roentgenium",
    "chineseName": "𬬭",
    "pinyin": "lún",
    "atomicMass": "282.169",
    "electronConfiguration": "[Rn]7s2 5f14 6d9 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      17,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "5, 3, 1, -1",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1994",
    "period": 7,
    "group": 11,
    "displayRow": 7,
    "displayColumn": 11
  },
  {
    "atomicNumber": 112,
    "symbol": "Cn",
    "englishName": "Copernicium",
    "chineseName": "鿔",
    "pinyin": "gē",
    "atomicMass": "286.179",
    "electronConfiguration": "[Rn]7s2 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      2
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "2, 1, 0",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "transition-metal",
    "categoryLabel": "过渡金属",
    "yearDiscovered": "1996",
    "period": 7,
    "group": 12,
    "displayRow": 7,
    "displayColumn": 12
  },
  {
    "atomicNumber": 113,
    "symbol": "Nh",
    "englishName": "Nihonium",
    "chineseName": "鿭",
    "pinyin": "nǐ",
    "atomicMass": "286.182",
    "electronConfiguration": "[Rn]5f14 6d10 7s2 7p1 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      3
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": null,
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "2004",
    "period": 7,
    "group": 13,
    "displayRow": 7,
    "displayColumn": 13
  },
  {
    "atomicNumber": 114,
    "symbol": "Fl",
    "englishName": "Flerovium",
    "chineseName": "𫓧",
    "pinyin": "fū",
    "atomicMass": "290.192",
    "electronConfiguration": "[Rn]7s2 7p2 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      4
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "6, 4,2, 1, 0",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "1998",
    "period": 7,
    "group": 14,
    "displayRow": 7,
    "displayColumn": 14
  },
  {
    "atomicNumber": 115,
    "symbol": "Mc",
    "englishName": "Moscovium",
    "chineseName": "镆",
    "pinyin": "mò",
    "atomicMass": "290.196",
    "electronConfiguration": "[Rn]7s2 7p3 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      5
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "3, 1",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "2003",
    "period": 7,
    "group": 15,
    "displayRow": 7,
    "displayColumn": 15
  },
  {
    "atomicNumber": 116,
    "symbol": "Lv",
    "englishName": "Livermorium",
    "chineseName": "𫟷",
    "pinyin": "lì",
    "atomicMass": "293.205",
    "electronConfiguration": "[Rn]7s2 7p4 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      6
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "+4, +2, -2",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "post-transition-metal",
    "categoryLabel": "其他金属",
    "yearDiscovered": "2000",
    "period": 7,
    "group": 16,
    "displayRow": 7,
    "displayColumn": 16
  },
  {
    "atomicNumber": 117,
    "symbol": "Ts",
    "englishName": "Tennessine",
    "chineseName": "鿬",
    "pinyin": "tián",
    "atomicMass": "294.211",
    "electronConfiguration": "[Rn]7s2 7p5 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      7
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "+5, +3, +1, -1",
    "standardState": "Expected to be a Solid",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "halogen",
    "categoryLabel": "卤素",
    "yearDiscovered": "2010",
    "period": 7,
    "group": 17,
    "displayRow": 7,
    "displayColumn": 17
  },
  {
    "atomicNumber": 118,
    "symbol": "Og",
    "englishName": "Oganesson",
    "chineseName": "鿫",
    "pinyin": "ào",
    "atomicMass": "295.216",
    "electronConfiguration": "[Rn]7s2 7p6 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      8
    ],
    "electronegativity": null,
    "atomicRadius": null,
    "ionizationEnergy": null,
    "electronAffinity": null,
    "oxidationStates": "+6, +4, +2, +1, 0, -1",
    "standardState": "Expected to be a Gas",
    "meltingPoint": null,
    "boilingPoint": null,
    "density": null,
    "category": "noble-gas",
    "categoryLabel": "稀有气体",
    "yearDiscovered": "2006",
    "period": 7,
    "group": 18,
    "displayRow": 7,
    "displayColumn": 18
  }
];
