import {
  createReaction,
  type GameLevel,
  type ReactionCategory,
  type ReactionDraft,
} from "./logic";

function r(
  id: string,
  title: string,
  equation: string,
  category: ReactionCategory,
  condition: string,
  description: string,
  observation: string,
  level?: GameLevel,
): ReactionDraft {
  return { id, title, equation, category, condition, description, observation, level };
}

const REACTION_DRAFTS: readonly ReactionDraft[] = [
  r("water-formation", "氢气燃烧生成水", "2 H₂ + O₂ -> 2 H₂O", "synthesis", "点燃", "氢气和氧气重新组合成水，常被用来说明燃烧也会生成新物质。", "释放能量并生成水"),
  r("ammonia-synthesis", "合成氨", "N₂ + 3 H₂ -> 2 NH₃", "synthesis", "工业过程", "空气中的氮与氢在工业设备中合成氨，是制造氮肥的重要起点。", "生成有刺激性气味的氨"),
  r("sodium-chloride", "钠与氯生成氯化钠", "2 Na + Cl₂ -> 2 NaCl", "synthesis", "专业演示", "两种性质很活泼的元素形成稳定的氯化钠，说明化合后性质可以完全改变。", "生成白色固体"),
  r("magnesium-oxide", "镁燃烧", "2 Mg + O₂ -> 2 MgO", "synthesis", "点燃", "镁与氧气结合生成氧化镁，是常见的金属燃烧示例。", "发出明亮白光并留下白色固体"),
  r("aluminium-oxide", "铝生成氧化铝", "4 Al + 3 O₂ -> 2 Al₂O₃", "synthesis", "接触空气", "铝表面会形成致密的氧化铝薄层，它像保护壳一样减慢继续氧化。", "表面形成很薄的保护层"),
  r("iron-oxide-three", "铁生成氧化铁", "4 Fe + 3 O₂ -> 2 Fe₂O₃", "synthesis", "氧气与水分参与", "铁在环境中逐渐氧化，氧化铁是铁锈的重要成分之一。", "逐渐出现红棕色物质"),
  r("magnetite-formation", "铁生成四氧化三铁", "3 Fe + 2 O₂ -> Fe₃O₄", "synthesis", "高温", "铁在特定条件下和氧结合形成四氧化三铁，这种黑色矿物具有磁性。", "生成黑色固体"),
  r("carbon-dioxide-formation", "碳充分燃烧", "C + O₂ -> CO₂", "combustion", "充分供氧", "含碳物质充分燃烧时，碳原子与氧原子组合成二氧化碳。", "生成无色二氧化碳"),
  r("carbon-monoxide-formation", "碳不充分燃烧", "2 C + O₂ -> 2 CO", "combustion", "氧气不足", "氧气不足时，碳可能形成有毒的一氧化碳，因此燃烧环境需要良好通风。", "生成无色有毒气体"),
  r("sulfur-dioxide-formation", "硫燃烧", "S + O₂ -> SO₂", "combustion", "点燃", "硫与氧气结合形成二氧化硫，这是认识空气污染物的一条常见反应。", "产生有刺激性气味的气体"),
  r("sulfur-trioxide", "二氧化硫继续氧化", "2 SO₂ + O₂ -> 2 SO₃", "synthesis", "工业催化", "二氧化硫进一步与氧结合生成三氧化硫，是工业制硫酸中的一个环节。", "反应可逆并释放热量"),
  r("phosphorus-oxide", "磷燃烧", "P₄ + 5 O₂ -> P₄O₁₀", "combustion", "专业演示", "磷在氧气中燃烧会形成磷的氧化物，只适合作为受控的专业演示。", "发光并产生白色烟雾"),
  r("calcium-oxide", "钙生成氧化钙", "2 Ca + O₂ -> 2 CaO", "synthesis", "加热", "钙与氧结合生成氧化钙，展示金属和氧气形成金属氧化物。", "生成白色固体"),
  r("slaked-lime", "生石灰变熟石灰", "CaO + H₂O -> Ca(OH)₂", "synthesis", "接触水", "氧化钙吸收水形成氢氧化钙，这一变化在建筑材料处理中很常见。", "明显放热"),
  r("sulfuric-acid-formation", "三氧化硫与水形成硫酸", "SO₃ + H₂O -> H₂SO₄", "synthesis", "工业密闭过程", "三氧化硫与水对应硫酸的组成关系，工业中需要在严格控制的设备内完成。", "强烈放热"),
  r("carbonic-acid-formation", "二氧化碳进入水", "CO₂ + H₂O -> H₂CO₃", "synthesis", "溶于水", "二氧化碳进入水后有一部分形成碳酸，汽水的轻微酸味与它有关。", "形成弱酸性溶液"),
  r("nitric-acid-formation", "五氧化二氮与水", "N₂O₅ + H₂O -> 2 HNO₃", "synthesis", "受控条件", "五氧化二氮和水的组成关系可以用来理解硝酸分子中的原子来源。", "形成酸性物质"),
  r("sodium-hydroxide-formation", "氧化钠与水", "Na₂O + H₂O -> 2 NaOH", "synthesis", "避免直接接触", "氧化钠和水形成氢氧化钠，属于碱性氧化物与水的反应。", "明显放热并形成碱性物质"),
  r("potassium-hydroxide-formation", "氧化钾与水", "K₂O + H₂O -> 2 KOH", "synthesis", "避免直接接触", "氧化钾与水形成氢氧化钾，展示一个氧化物可以生成碱。", "明显放热"),
  r("copper-oxide", "铜生成氧化铜", "2 Cu + O₂ -> 2 CuO", "synthesis", "加热", "铜受热时表面与氧结合形成黑色氧化铜。", "红色铜表面逐渐变黑"),

  r("hydrogen-peroxide-decomposition", "过氧化氢分解", "2 H₂O₂ -> 2 H₂O + O₂", "decomposition", "缓慢分解", "过氧化氢会逐渐变成水和氧气，因此通常装在避光容器里。", "产生氧气气泡"),
  r("water-electrolysis", "水的电解", "2 H₂O -> 2 H₂ + O₂", "decomposition", "通入电能", "电能可以让水分子重新排列为氢气和氧气，左右气体体积约为二比一。", "两侧产生气泡"),
  r("potassium-chlorate-decomposition", "氯酸钾分解", "2 KClO₃ -> 2 KCl + 3 O₂", "decomposition", "专业受控加热", "氯酸钾在专业条件下可分解并释放氧气，不适合作为家庭实验。", "产生氧气"),
  r("potassium-permanganate-decomposition", "高锰酸钾受热分解", "2 KMnO₄ -> K₂MnO₄ + MnO₂ + O₂", "decomposition", "专业受控加热", "高锰酸钾受热时原子重新组合，并有氧气生成。", "固体颜色变化并放出氧气"),
  r("limestone-decomposition", "石灰石煅烧", "CaCO₃ -> CaO + CO₂", "decomposition", "工业高温", "石灰石受热分解生成氧化钙和二氧化碳，是生产石灰和水泥的重要变化。", "固体质量变化并放出气体"),
  r("baking-soda-decomposition", "小苏打受热分解", "2 NaHCO₃ -> Na₂CO₃ + H₂O + CO₂", "decomposition", "受热", "小苏打受热产生水和二氧化碳，气体能帮助面点形成疏松结构。", "产生气体"),
  r("malachite-decomposition", "碱式碳酸铜分解", "Cu₂(OH)₂CO₃ -> 2 CuO + H₂O + CO₂", "decomposition", "专业受控加热", "绿色碱式碳酸铜受热时形成黑色氧化铜，同时放出水和二氧化碳。", "绿色固体变黑并放出气体"),
  r("mercury-oxide-decomposition", "氧化汞分解", "2 HgO -> 2 Hg + O₂", "decomposition", "仅作历史认识", "这条历史反应帮助科学家认识氧气，但汞有毒，页面只用于理解守恒。", "生成汞和氧气"),
  r("silver-oxide-decomposition", "氧化银分解", "2 Ag₂O -> 4 Ag + O₂", "decomposition", "受热或见光", "氧化银可以分解为银和氧气，展示化合物变成多种物质。", "形成银并释放氧气"),
  r("iron-hydroxide-decomposition", "氢氧化铁分解", "2 Fe(OH)₃ -> Fe₂O₃ + 3 H₂O", "decomposition", "受热", "氢氧化铁失去水后形成氧化铁，可帮助理解沉淀受热变化。", "生成红棕色氧化物"),
  r("carbonic-acid-decomposition", "碳酸分解", "H₂CO₃ -> H₂O + CO₂", "decomposition", "自然发生", "碳酸不稳定，会重新变成水和二氧化碳，汽水开盖冒泡与此有关。", "二氧化碳逸出"),
  r("ammonium-bicarbonate-decomposition", "碳酸氢铵分解", "NH₄HCO₃ -> NH₃ + H₂O + CO₂", "decomposition", "受热", "碳酸氢铵受热会生成三种气体或蒸气，过去也曾用于食品膨松。", "产生多种气体"),
  r("ammonia-decomposition", "氨分解", "2 NH₃ -> N₂ + 3 H₂", "decomposition", "高温催化", "氨在特定工业条件下可分解成氮气和氢气。", "生成两种无色气体"),
  r("airbag-reaction", "安全气囊产气示意", "2 NaN₃ -> 2 Na + 3 N₂", "decomposition", "汽车安全装置", "经典安全气囊教材用式展示固体如何快速产生氮气；实际装置包含完整安全处理。", "迅速产生氮气"),
  r("ozone-decomposition", "臭氧变成氧气", "2 O₃ -> 3 O₂", "decomposition", "自然与催化过程", "臭氧分子可以重新排列成更稳定的氧气分子。", "臭氧减少、氧气增加"),
  r("magnesium-carbonate-decomposition", "碳酸镁分解", "MgCO₃ -> MgO + CO₂", "decomposition", "加热", "碳酸镁受热生成氧化镁和二氧化碳。", "放出二氧化碳"),
  r("copper-hydroxide-decomposition", "氢氧化铜分解", "Cu(OH)₂ -> CuO + H₂O", "decomposition", "受热", "蓝色氢氧化铜受热变为黑色氧化铜和水。", "蓝色固体逐渐变黑"),
  r("aluminium-hydroxide-decomposition", "氢氧化铝分解", "2 Al(OH)₃ -> Al₂O₃ + 3 H₂O", "decomposition", "受热", "氢氧化铝受热失去水并形成氧化铝。", "形成白色氧化物"),

  r("zinc-hydrochloric", "锌与盐酸", "Zn + 2 HCl -> ZnCl₂ + H₂", "replacement", "专业演示", "锌把酸中的氢置换出来，生成氯化锌和氢气。", "金属表面出现气泡"),
  r("iron-hydrochloric", "铁与盐酸", "Fe + 2 HCl -> FeCl₂ + H₂", "replacement", "专业演示", "铁与稀酸作用，铁进入溶液并放出氢气。", "产生气泡，溶液呈浅绿色"),
  r("magnesium-hydrochloric", "镁与盐酸", "Mg + 2 HCl -> MgCl₂ + H₂", "replacement", "专业演示", "镁比氢活泼，可以把酸中的氢置换成氢气。", "快速产生气泡"),
  r("aluminium-hydrochloric", "铝与盐酸", "2 Al + 6 HCl -> 2 AlCl₃ + 3 H₂", "replacement", "专业演示", "去除表面保护层后，铝能与酸反应并释放氢气。", "产生气泡并放热"),
  r("sodium-water", "钠与水", "2 Na + 2 H₂O -> 2 NaOH + H₂", "replacement", "仅作专业演示", "钠与水反应非常剧烈，页面只用于观察原子守恒，不可模仿。", "快速移动、放热并产生气体"),
  r("calcium-water", "钙与水", "Ca + 2 H₂O -> Ca(OH)₂ + H₂", "replacement", "受控条件", "钙能从水中置换出氢，生成微溶的氢氧化钙。", "出现气泡和白色浑浊"),
  r("iron-steam", "铁与水蒸气", "3 Fe + 4 H₂O -> Fe₃O₄ + 4 H₂", "replacement", "高温水蒸气", "高温下铁与水蒸气反应，生成四氧化三铁和氢气。", "生成黑色固体和氢气"),
  r("iron-copper-sulfate", "铁置换铜", "Fe + CuSO₄ -> FeSO₄ + Cu", "replacement", "溶液中", "铁比铜活泼，可以把硫酸铜中的铜置换出来。", "蓝色变浅，铁表面出现红色铜"),
  r("zinc-copper-sulfate", "锌置换铜", "Zn + CuSO₄ -> ZnSO₄ + Cu", "replacement", "溶液中", "锌把硫酸铜中的铜置换出来，是金属活动性顺序的常见例子。", "蓝色变浅并析出铜"),
  r("copper-silver-nitrate", "铜置换银", "Cu + 2 AgNO₃ -> Cu(NO₃)₂ + 2 Ag", "replacement", "专业演示", "铜进入溶液，同时银从溶液中析出，体现原子重新分配。", "出现银色晶体，溶液变蓝"),
  r("chlorine-potassium-bromide", "氯置换溴", "Cl₂ + 2 KBr -> 2 KCl + Br₂", "replacement", "专业密闭演示", "更活泼的氯可以把溴从溴化物中置换出来。", "出现溴的颜色"),
  r("bromine-potassium-iodide", "溴置换碘", "Br₂ + 2 KI -> 2 KBr + I₂", "replacement", "专业密闭演示", "溴能把碘从碘化物中置换出来，展示卤素活动性的差异。", "出现碘的颜色"),
  r("thermite", "铝热反应", "2 Al + Fe₂O₃ -> Al₂O₃ + 2 Fe", "redox", "工业与专业操作", "铝夺取氧化铁中的氧并生成铁，实际过程温度极高，绝不能自行尝试。", "释放大量热并形成熔融铁"),
  r("zinc-silver-nitrate", "锌置换银", "Zn + 2 AgNO₃ -> Zn(NO₃)₂ + 2 Ag", "replacement", "专业演示", "锌比银活泼，会进入溶液并让银析出。", "锌表面出现银色晶体"),
  r("magnesium-copper-sulfate", "镁置换铜", "Mg + CuSO₄ -> MgSO₄ + Cu", "replacement", "专业演示", "镁把硫酸铜中的铜置换出来，说明镁的活动性更强。", "蓝色变浅并析出铜"),
  r("potassium-water", "钾与水", "2 K + 2 H₂O -> 2 KOH + H₂", "replacement", "仅作虚拟认识", "钾与水的反应非常剧烈，只用于认识系数和守恒，不可模仿。", "剧烈放热并产生气体"),
  r("lithium-water", "锂与水", "2 Li + 2 H₂O -> 2 LiOH + H₂", "replacement", "专业演示", "锂与水反应生成氢氧化锂和氢气，速度比钠和钾温和。", "缓慢产生气泡"),
  r("fluorine-water", "氟与水的总反应", "2 F₂ + 2 H₂O -> 4 HF + O₂", "redox", "仅作理论认识", "氟反应性极强，这个总反应只用于学习守恒，绝不能实验。", "强烈反应"),
  r("magnesium-carbon-dioxide", "镁在二氧化碳中燃烧", "2 Mg + CO₂ -> 2 MgO + C", "redox", "专业演示", "非常活泼的镁能从二氧化碳中夺取氧，说明二氧化碳并非对所有燃烧都有效。", "明亮白光并生成黑色碳"),
  r("chlorine-potassium-iodide", "氯置换碘", "Cl₂ + 2 KI -> 2 KCl + I₂", "replacement", "专业密闭演示", "氯能把碘从碘化钾中置换出来。", "出现碘的颜色"),

  r("silver-chloride-precipitation", "氯化银沉淀", "AgNO₃ + NaCl -> AgCl + NaNO₃", "exchange", "溶液混合", "银离子和氯离子相遇形成难溶的氯化银。", "出现白色沉淀"),
  r("barium-sulfate-precipitation", "硫酸钡沉淀", "BaCl₂ + Na₂SO₄ -> BaSO₄ + 2 NaCl", "exchange", "专业演示", "钡离子和硫酸根形成难溶的硫酸钡，医学造影使用的是严格制备的硫酸钡。", "出现白色沉淀"),
  r("calcium-carbonate-precipitation", "碳酸钙沉淀", "CaCl₂ + Na₂CO₃ -> CaCO₃ + 2 NaCl", "exchange", "溶液混合", "钙离子和碳酸根结合生成碳酸钙，岩石和贝壳中也常见这种物质。", "出现白色沉淀"),
  r("lead-iodide-precipitation", "碘化铅沉淀", "Pb(NO₃)₂ + 2 KI -> PbI₂ + 2 KNO₃", "exchange", "仅作专业演示", "黄色碘化铅沉淀常用于展示离子交换，但铅盐有毒。", "出现黄色沉淀"),
  r("copper-hydroxide-precipitation", "氢氧化铜沉淀", "CuSO₄ + 2 NaOH -> Cu(OH)₂ + Na₂SO₄", "exchange", "专业演示", "铜离子与氢氧根结合，生成蓝色氢氧化铜沉淀。", "出现蓝色沉淀"),
  r("iron-three-hydroxide-precipitation", "氢氧化铁沉淀", "FeCl₃ + 3 NaOH -> Fe(OH)₃ + 3 NaCl", "exchange", "专业演示", "铁离子和氢氧根形成红棕色氢氧化铁。", "出现红棕色沉淀"),
  r("aluminium-hydroxide-precipitation", "氢氧化铝沉淀", "AlCl₃ + 3 NaOH -> Al(OH)₃ + 3 NaCl", "exchange", "受控用量", "铝离子和氢氧根形成白色胶状氢氧化铝。", "出现白色胶状沉淀"),
  r("magnesium-hydroxide-precipitation", "氢氧化镁沉淀", "MgCl₂ + 2 NaOH -> Mg(OH)₂ + 2 NaCl", "exchange", "溶液混合", "镁离子与氢氧根形成难溶的氢氧化镁。", "出现白色沉淀"),
  r("carbonate-acid", "碳酸钠遇酸", "Na₂CO₃ + 2 HCl -> 2 NaCl + H₂O + CO₂", "exchange", "专业演示", "碳酸盐遇酸会形成水并放出二氧化碳。", "快速产生气泡"),
  r("bicarbonate-acid", "小苏打遇酸", "NaHCO₃ + HCl -> NaCl + H₂O + CO₂", "exchange", "受控演示", "碳酸氢钠遇酸放出二氧化碳，这是许多膨松和泡腾现象的化学基础。", "产生大量小气泡"),
  r("limestone-acid", "碳酸钙遇酸", "CaCO₃ + 2 HCl -> CaCl₂ + H₂O + CO₂", "exchange", "专业演示", "碳酸钙遇酸放出二氧化碳，也解释了酸会侵蚀石灰岩。", "固体表面冒泡"),
  r("sulfite-acid", "亚硫酸钠遇酸", "Na₂SO₃ + 2 HCl -> 2 NaCl + H₂O + SO₂", "exchange", "通风的专业环境", "亚硫酸盐遇酸会放出有刺激性的二氧化硫，只作虚拟认识。", "产生有刺激性气味的气体"),
  r("sulfide-acid", "硫化钠遇酸", "Na₂S + 2 HCl -> 2 NaCl + H₂S", "exchange", "仅作理论认识", "硫化物遇酸可能放出剧毒硫化氢，页面只用于配平，绝不能尝试。", "产生有毒气体"),
  r("ammonium-chloride-base", "铵盐与碱", "NH₄Cl + NaOH -> NaCl + NH₃ + H₂O", "exchange", "专业通风环境", "铵盐与碱作用会放出氨，可用于认识铵根中的氮和氢去了哪里。", "产生有刺激性气味的氨"),
  r("ammonium-sulfate-base", "硫酸铵与碱", "(NH₄)₂SO₄ + 2 NaOH -> Na₂SO₄ + 2 NH₃ + 2 H₂O", "exchange", "专业通风环境", "硫酸铵与碱作用生成氨、水和硫酸钠。", "放出氨气"),
  r("silver-bromide-precipitation", "溴化银沉淀", "AgNO₃ + KBr -> AgBr + KNO₃", "exchange", "避光演示", "银离子和溴离子形成感光的溴化银沉淀。", "出现淡黄色沉淀"),
  r("silver-carbonate-precipitation", "碳酸银沉淀", "2 AgNO₃ + Na₂CO₃ -> Ag₂CO₃ + 2 NaNO₃", "exchange", "专业演示", "银离子与碳酸根形成难溶的碳酸银。", "出现浅黄色沉淀"),
  r("calcium-phosphate-precipitation", "磷酸钙沉淀", "3 CaCl₂ + 2 Na₃PO₄ -> Ca₃(PO₄)₂ + 6 NaCl", "exchange", "溶液混合", "钙离子和磷酸根形成磷酸钙，骨骼矿物也含相关钙磷结构。", "出现白色沉淀"),
  r("iron-two-hydroxide-precipitation", "氢氧化亚铁沉淀", "FeSO₄ + 2 NaOH -> Fe(OH)₂ + Na₂SO₄", "exchange", "隔绝空气观察", "亚铁离子与氢氧根形成浅绿色沉淀，接触空气后还会继续变化。", "出现浅绿色沉淀"),
  r("copper-chloride-base", "氯化铜与碱", "CuCl₂ + 2 NaOH -> Cu(OH)₂ + 2 NaCl", "exchange", "专业演示", "氯化铜中的铜离子与氢氧根结合成蓝色沉淀。", "出现蓝色沉淀"),
  r("barium-nitrate-sulfate", "硝酸钡与硫酸钠", "Ba(NO₃)₂ + Na₂SO₄ -> BaSO₄ + 2 NaNO₃", "exchange", "专业演示", "不同来源的钡离子和硫酸根仍会形成硫酸钡沉淀。", "出现白色沉淀"),
  r("iron-two-chloride-base", "氯化亚铁与碱", "FeCl₂ + 2 NaOH -> Fe(OH)₂ + 2 NaCl", "exchange", "专业演示", "亚铁离子和氢氧根形成氢氧化亚铁。", "出现浅绿色沉淀"),
  r("zinc-hydroxide-precipitation", "氢氧化锌沉淀", "ZnSO₄ + 2 NaOH -> Zn(OH)₂ + Na₂SO₄", "exchange", "受控用量", "锌离子和氢氧根形成白色氢氧化锌。", "出现白色沉淀"),
  r("aluminium-sulfate-barium", "硫酸铝与氯化钡", "Al₂(SO₄)₃ + 3 BaCl₂ -> 3 BaSO₄ + 2 AlCl₃", "exchange", "专业演示", "三个硫酸根分别与钡离子形成三份硫酸钡，适合观察括号外系数。", "出现大量白色沉淀"),
  r("copper-sulfate-barium", "硫酸铜与氯化钡", "CuSO₄ + BaCl₂ -> BaSO₄ + CuCl₂", "exchange", "专业演示", "硫酸铜提供硫酸根，与钡离子形成硫酸钡。", "蓝色溶液中出现白色沉淀"),
  r("calcium-nitrate-carbonate", "硝酸钙与碳酸钠", "Ca(NO₃)₂ + Na₂CO₃ -> CaCO₃ + 2 NaNO₃", "exchange", "溶液混合", "钙离子和碳酸根形成碳酸钙沉淀。", "出现白色沉淀"),
  r("magnesium-sulfate-barium", "硫酸镁与氯化钡", "MgSO₄ + BaCl₂ -> BaSO₄ + MgCl₂", "exchange", "专业演示", "硫酸镁中的硫酸根与钡离子结合成难溶固体。", "出现白色沉淀"),

  r("hydrochloric-sodium-hydroxide", "盐酸与氢氧化钠", "HCl + NaOH -> NaCl + H₂O", "neutralization", "酸碱中和", "酸和碱互相反应生成盐和水，是最基础的中和反应之一。", "温度可能略微升高"),
  r("sulfuric-sodium-hydroxide", "硫酸与氢氧化钠", "H₂SO₄ + 2 NaOH -> Na₂SO₄ + 2 H₂O", "neutralization", "酸碱中和", "一个硫酸分子需要两份氢氧化钠完全中和。", "放出热量"),
  r("sulfuric-potassium-hydroxide", "硫酸与氢氧化钾", "H₂SO₄ + 2 KOH -> K₂SO₄ + 2 H₂O", "neutralization", "酸碱中和", "硫酸和氢氧化钾形成硫酸钾和水。", "放出热量"),
  r("hydrochloric-calcium-hydroxide", "盐酸与氢氧化钙", "2 HCl + Ca(OH)₂ -> CaCl₂ + 2 H₂O", "neutralization", "酸碱中和", "两份盐酸与一份氢氧化钙完全中和。", "碱性逐渐减弱"),
  r("hydrochloric-aluminium-hydroxide", "盐酸与氢氧化铝", "3 HCl + Al(OH)₃ -> AlCl₃ + 3 H₂O", "neutralization", "专业条件", "氢氧化铝中的三个氢氧根分别与酸中的氢形成水。", "白色固体逐渐溶解"),
  r("phosphoric-sodium-hydroxide", "磷酸完全中和", "H₃PO₄ + 3 NaOH -> Na₃PO₄ + 3 H₂O", "neutralization", "完全中和", "磷酸有三个可参与中和的氢，因此需要三份氢氧化钠。", "形成磷酸钠和水"),
  r("nitric-calcium-hydroxide", "硝酸与氢氧化钙", "2 HNO₃ + Ca(OH)₂ -> Ca(NO₃)₂ + 2 H₂O", "neutralization", "酸碱中和", "硝酸和氢氧化钙生成硝酸钙和水。", "放出少量热"),
  r("carbonic-potassium-hydroxide", "碳酸完全中和", "H₂CO₃ + 2 KOH -> K₂CO₃ + 2 H₂O", "neutralization", "完全中和", "碳酸与足量氢氧化钾形成碳酸钾和水。", "酸性减弱"),
  r("sulfuric-barium-hydroxide", "硫酸与氢氧化钡", "H₂SO₄ + Ba(OH)₂ -> BaSO₄ + 2 H₂O", "neutralization", "专业演示", "这次中和既生成水，也生成难溶的硫酸钡。", "出现白色沉淀并放热"),
  r("nitric-potassium-hydroxide", "硝酸与氢氧化钾", "HNO₃ + KOH -> KNO₃ + H₂O", "neutralization", "酸碱中和", "硝酸与氢氧化钾生成硝酸钾和水。", "放出少量热"),
  r("copper-oxide-hydrochloric", "氧化铜与盐酸", "CuO + 2 HCl -> CuCl₂ + H₂O", "neutralization", "专业演示", "黑色氧化铜与酸反应形成可溶的铜盐和水。", "黑色固体溶解，溶液呈蓝绿色"),
  r("iron-oxide-hydrochloric", "氧化铁与盐酸", "Fe₂O₃ + 6 HCl -> 2 FeCl₃ + 3 H₂O", "neutralization", "专业演示", "酸能与氧化铁反应，这与酸洗除铁锈的化学原理相关。", "红棕色固体逐渐溶解"),
  r("aluminium-oxide-hydrochloric", "氧化铝与盐酸", "Al₂O₃ + 6 HCl -> 2 AlCl₃ + 3 H₂O", "neutralization", "专业条件", "氧化铝与酸形成铝盐和水。", "固体逐渐溶解"),
  r("magnesium-oxide-hydrochloric", "氧化镁与盐酸", "MgO + 2 HCl -> MgCl₂ + H₂O", "neutralization", "酸碱反应", "氧化镁是碱性氧化物，可以与酸生成盐和水。", "白色固体逐渐溶解"),
  r("calcium-oxide-hydrochloric", "氧化钙与盐酸", "CaO + 2 HCl -> CaCl₂ + H₂O", "neutralization", "专业演示", "氧化钙与盐酸形成氯化钙和水。", "放出热量"),
  r("zinc-oxide-hydrochloric", "氧化锌与盐酸", "ZnO + 2 HCl -> ZnCl₂ + H₂O", "neutralization", "专业演示", "氧化锌与酸生成锌盐和水。", "白色固体逐渐溶解"),
  r("sodium-oxide-hydrochloric", "氧化钠与盐酸", "Na₂O + 2 HCl -> 2 NaCl + H₂O", "neutralization", "仅作组成认识", "氧化钠与盐酸形成氯化钠和水。", "强烈放热"),
  r("potassium-oxide-hydrochloric", "氧化钾与盐酸", "K₂O + 2 HCl -> 2 KCl + H₂O", "neutralization", "仅作组成认识", "氧化钾与酸形成盐和水。", "强烈放热"),
  r("copper-oxide-sulfuric", "氧化铜与硫酸", "CuO + H₂SO₄ -> CuSO₄ + H₂O", "neutralization", "专业演示", "黑色氧化铜与硫酸形成蓝色硫酸铜溶液。", "黑色固体消失，溶液变蓝"),
  r("zinc-oxide-sulfuric", "氧化锌与硫酸", "ZnO + H₂SO₄ -> ZnSO₄ + H₂O", "neutralization", "专业演示", "氧化锌和硫酸形成硫酸锌和水。", "白色固体逐渐溶解"),
  r("iron-oxide-sulfuric", "氧化铁与硫酸", "Fe₂O₃ + 3 H₂SO₄ -> Fe₂(SO₄)₃ + 3 H₂O", "neutralization", "专业演示", "氧化铁与硫酸形成硫酸铁和水。", "红棕色固体逐渐溶解"),
  r("aluminium-oxide-sulfuric", "氧化铝与硫酸", "Al₂O₃ + 3 H₂SO₄ -> Al₂(SO₄)₃ + 3 H₂O", "neutralization", "专业条件", "氧化铝与硫酸形成硫酸铝和水。", "固体逐渐溶解"),

  r("methane-combustion", "甲烷充分燃烧", "CH₄ + 2 O₂ -> CO₂ + 2 H₂O", "combustion", "充分供氧", "天然气的主要成分甲烷充分燃烧，生成二氧化碳和水。", "蓝色火焰并释放热量"),
  r("ethane-combustion", "乙烷充分燃烧", "2 C₂H₆ + 7 O₂ -> 4 CO₂ + 6 H₂O", "combustion", "充分供氧", "乙烷燃烧时，碳进入二氧化碳，氢进入水。", "放出光和热"),
  r("propane-combustion", "丙烷充分燃烧", "C₃H₈ + 5 O₂ -> 3 CO₂ + 4 H₂O", "combustion", "充分供氧", "瓶装燃气中常见的丙烷充分燃烧生成二氧化碳和水。", "蓝色火焰并放热"),
  r("butane-combustion", "丁烷充分燃烧", "2 C₄H₁₀ + 13 O₂ -> 8 CO₂ + 10 H₂O", "combustion", "充分供氧", "丁烷燃烧需要较多氧气，配平时要同时照顾碳、氢和氧。", "放出光和热"),
  r("ethylene-combustion", "乙烯充分燃烧", "C₂H₄ + 3 O₂ -> 2 CO₂ + 2 H₂O", "combustion", "充分供氧", "乙烯充分燃烧生成二氧化碳和水。", "明亮火焰并放热"),
  r("acetylene-combustion", "乙炔充分燃烧", "2 C₂H₂ + 5 O₂ -> 4 CO₂ + 2 H₂O", "combustion", "充分供氧", "乙炔与充足氧气燃烧能产生高温火焰，工业上用于金属加工。", "强光和高温"),
  r("ethanol-combustion", "乙醇充分燃烧", "C₂H₆O + 3 O₂ -> 2 CO₂ + 3 H₂O", "combustion", "充分供氧", "乙醇燃烧时自身已经带有一个氧原子，最终形成二氧化碳和水。", "淡蓝色火焰"),
  r("methanol-combustion", "甲醇充分燃烧", "2 CH₄O + 3 O₂ -> 2 CO₂ + 4 H₂O", "combustion", "专业受控燃烧", "甲醇燃烧生成二氧化碳和水，但甲醇有毒，不可接触或模仿。", "火焰较淡并放热"),
  r("glucose-respiration", "葡萄糖的有氧分解", "C₆H₁₂O₆ + 6 O₂ -> 6 CO₂ + 6 H₂O", "life", "细胞中的多步过程", "细胞通过许多步骤利用葡萄糖和氧气释放能量，总反应可写成这条守恒方程。", "释放生命活动可利用的能量"),
  r("benzene-combustion", "苯充分燃烧", "2 C₆H₆ + 15 O₂ -> 12 CO₂ + 6 H₂O", "combustion", "仅作理论认识", "苯燃烧的配平系数较大，适合挑战同时守恒三种元素。", "放热；苯有毒不可接触"),
  r("hydrogen-sulfide-combustion", "硫化氢燃烧", "2 H₂S + 3 O₂ -> 2 SO₂ + 2 H₂O", "combustion", "工业安全处理", "有毒硫化氢在受控条件下氧化为二氧化硫和水。", "放热并生成刺激性气体"),
  r("carbon-disulfide-combustion", "二硫化碳燃烧", "CS₂ + 3 O₂ -> CO₂ + 2 SO₂", "combustion", "仅作理论认识", "二硫化碳易燃且有毒，页面只用于观察碳、硫、氧如何守恒。", "放出热并生成两种氧化物"),
  r("pyrite-roasting", "黄铁矿焙烧", "4 FeS₂ + 11 O₂ -> 2 Fe₂O₃ + 8 SO₂", "redox", "工业高温", "含硫矿物在工业炉中与氧气反应，生成氧化铁和二氧化硫。", "固体变化并产生气体"),
  r("carbon-monoxide-combustion", "一氧化碳燃烧", "2 CO + O₂ -> 2 CO₂", "combustion", "点燃", "有毒的一氧化碳进一步与氧结合成为二氧化碳。", "蓝色火焰并放热"),
  r("ammonia-oxygen-nitrogen", "氨在氧气中燃烧", "4 NH₃ + 3 O₂ -> 2 N₂ + 6 H₂O", "combustion", "特定条件", "氨在某些条件下燃烧生成氮气和水。", "放热并生成水蒸气"),
  r("ammonia-catalytic-oxidation", "氨的催化氧化", "4 NH₃ + 5 O₂ -> 4 NO + 6 H₂O", "redox", "工业催化", "氨在工业催化条件下生成一氧化氮，是制造硝酸的起始步骤。", "放热并生成无色气体"),

  r("nitric-oxide-formation", "氮气与氧气生成一氧化氮", "N₂ + O₂ -> 2 NO", "redox", "高温", "空气中的氮和氧在高温下可形成一氧化氮，发动机和闪电环境中可能发生。", "生成无色气体"),
  r("nitrogen-dioxide-formation", "一氧化氮继续氧化", "2 NO + O₂ -> 2 NO₂", "redox", "接触空气", "一氧化氮遇空气中的氧会变成棕红色二氧化氮。", "无色气体逐渐变棕红"),
  r("nitrogen-dioxide-water", "二氧化氮与水", "3 NO₂ + H₂O -> 2 HNO₃ + NO", "redox", "大气与工业过程", "二氧化氮与水作用可形成硝酸和一氧化氮，与酸雨形成有关。", "形成酸性物质"),
  r("chlor-alkali", "食盐水电解总反应", "2 NaCl + 2 H₂O -> 2 NaOH + H₂ + Cl₂", "redox", "工业电解", "氯碱工业利用电能把食盐水转变为氢氧化钠、氢气和氯气。", "不同电极产生气体"),
  r("aluminium-electrolysis", "氧化铝电解总式", "2 Al₂O₃ -> 4 Al + 3 O₂", "decomposition", "工业电解示意", "这条简化总式展示氧化铝中铝和氧的数量关系；实际炼铝过程更复杂。", "获得铝并发生电极反应"),
  r("hematite-carbon-monoxide", "一氧化碳还原氧化铁", "Fe₂O₃ + 3 CO -> 2 Fe + 3 CO₂", "redox", "工业高温", "高炉中一氧化碳夺取铁矿石中的氧，帮助得到铁。", "氧化物减少并形成铁"),
  r("magnetite-carbon-monoxide", "一氧化碳还原四氧化三铁", "Fe₃O₄ + 4 CO -> 3 Fe + 4 CO₂", "redox", "工业高温", "一氧化碳把四氧化三铁中的氧带走，最终生成铁和二氧化碳。", "形成金属铁"),
  r("zinc-oxide-carbon", "碳还原氧化锌", "ZnO + C -> Zn + CO", "redox", "工业高温", "碳在高温下帮助氧化锌失去氧，生成锌和一氧化碳。", "生成锌蒸气和气体"),
  r("copper-oxide-carbon", "碳还原氧化亚铜", "2 Cu₂O + C -> 4 Cu + CO₂", "redox", "高温", "碳夺取氧化亚铜中的氧，铜原子重新形成金属铜。", "形成红色铜"),
  r("silicon-production", "二氧化硅与碳", "SiO₂ + 2 C -> Si + 2 CO", "redox", "工业电炉", "工业电炉中碳帮助二氧化硅失去氧，得到硅。", "高温下生成硅和气体"),
  r("slag-formation", "炉渣形成", "CaCO₃ + SiO₂ -> CaSiO₃ + CO₂", "redox", "工业高温", "炼铁时石灰石相关物质与二氧化硅形成炉渣，帮助带走杂质。", "形成熔融炉渣并放出气体"),
  r("lead-acid-battery", "铅蓄电池放电总反应", "Pb + PbO₂ + 2 H₂SO₄ -> 2 PbSO₄ + 2 H₂O", "redox", "电池内部", "铅蓄电池放电时，两块电极材料都逐渐转变为硫酸铅，并生成水。", "化学能转变为电能", "challenge"),
  r("copper-oxide-hydrogen", "氢气还原氧化铜", "CuO + H₂ -> Cu + H₂O", "redox", "专业加热", "氢气夺取氧化铜中的氧形成水，留下铜。", "黑色固体变成红色铜"),
  r("iron-oxide-hydrogen", "氢气还原氧化铁", "Fe₂O₃ + 3 H₂ -> 2 Fe + 3 H₂O", "redox", "工业研究条件", "氢气可以作为还原剂带走氧化铁中的氧，被研究用于低碳炼铁。", "形成铁和水"),
  r("tungsten-oxide-hydrogen", "氢气还原氧化钨", "WO₃ + 3 H₂ -> W + 3 H₂O", "redox", "工业高温", "工业上可用氢把氧化钨还原成金属钨。", "形成灰色钨粉"),
  r("copper-oxide-carbon-two", "碳还原氧化铜", "2 CuO + C -> 2 Cu + CO₂", "redox", "高温", "碳夺取氧化铜中的氧，生成铜和二氧化碳。", "黑色固体中出现红色铜"),
  r("lead-oxide-carbon-monoxide", "一氧化碳还原氧化铅", "PbO + CO -> Pb + CO₂", "redox", "仅作理论认识", "一氧化碳带走氧化铅中的氧；铅及其化合物有毒。", "形成铅和二氧化碳"),
  r("tin-oxide-carbon-monoxide", "一氧化碳还原氧化锡", "SnO₂ + 2 CO -> Sn + 2 CO₂", "redox", "工业高温", "一氧化碳夺取氧化锡中的氧，形成锡。", "形成金属锡"),
  r("manganese-dioxide-hydrochloric", "二氧化锰与盐酸", "MnO₂ + 4 HCl -> MnCl₂ + Cl₂ + 2 H₂O", "redox", "仅作专业认识", "这条经典反应会产生有毒氯气，只用于学习电子转移和守恒。", "生成黄绿色气体"),
  r("iron-two-chloride-oxidation", "氯化亚铁被氯氧化", "2 FeCl₂ + Cl₂ -> 2 FeCl₃", "redox", "专业密闭条件", "氯把二价铁转变为三价铁，所有铁和氯原子仍然守恒。", "溶液颜色改变"),

  r("photosynthesis", "光合作用总反应", "6 CO₂ + 6 H₂O -> C₆H₁₂O₆ + 6 O₂", "life", "光照与叶绿体", "绿色植物利用光能，把二氧化碳和水逐步转变为储存能量的糖并释放氧气。", "光能转变为化学能"),
  r("alcohol-fermentation", "酒精发酵总反应", "C₆H₁₂O₆ -> 2 C₂H₆O + 2 CO₂", "life", "微生物参与", "酵母在缺氧环境中把葡萄糖转变为乙醇和二氧化碳。", "产生二氧化碳气泡"),
  r("lactic-fermentation", "乳酸发酵总反应", "C₆H₁₂O₆ -> 2 C₃H₆O₃", "life", "微生物或细胞过程", "一些微生物和细胞能把葡萄糖转变为乳酸。", "形成乳酸"),
  r("limewater-carbon-dioxide", "二氧化碳检验", "CO₂ + Ca(OH)₂ -> CaCO₃ + H₂O", "life", "气体通入溶液", "二氧化碳与澄清石灰水形成碳酸钙，常用于帮助识别二氧化碳。", "澄清溶液变浑浊"),
  r("sulfur-dioxide-lime", "石灰吸收二氧化硫", "SO₂ + Ca(OH)₂ -> CaSO₃ + H₂O", "life", "烟气净化", "工业烟气处理中，石灰类物质可以吸收二氧化硫，减少它进入空气。", "形成亚硫酸钙固体"),
  r("sodium-peroxide-carbon-dioxide", "过氧化钠吸收二氧化碳", "2 CO₂ + 2 Na₂O₂ -> 2 Na₂CO₃ + O₂", "life", "密闭空气处理示意", "过氧化钠可吸收二氧化碳并释放氧气，曾用于特殊密闭环境。", "二氧化碳减少并产生氧气"),
  r("potassium-superoxide-carbon-dioxide", "超氧化钾净化空气", "4 KO₂ + 2 CO₂ -> 2 K₂CO₃ + 3 O₂", "life", "专业空气再生装置", "超氧化钾能在专业装置中吸收二氧化碳并释放氧气。", "二氧化碳减少、氧气增加"),
  r("ethylene-hydrogenation", "乙烯加氢", "C₂H₄ + H₂ -> C₂H₆", "synthesis", "工业催化", "乙烯分子加入氢后形成乙烷，碳原子数量保持不变。", "双键结构发生改变"),
  r("acetylene-hydrogenation", "乙炔完全加氢", "C₂H₂ + 2 H₂ -> C₂H₆", "synthesis", "工业催化", "乙炔逐步加入氢，最终形成乙烷。", "不饱和结构变为饱和结构"),
  r("ethylene-hydration", "乙烯水合", "C₂H₄ + H₂O -> C₂H₆O", "synthesis", "工业催化", "乙烯和水的原子重新排列可形成乙醇。", "生成乙醇"),
  r("acetylene-hydrochloride", "乙炔加氯化氢", "C₂H₂ + HCl -> C₂H₃Cl", "synthesis", "工业过程", "乙炔与氯化氢的原子组合成氯乙烯，后者是材料工业的原料。", "形成新的有机分子"),
  r("ethylene-chlorine", "乙烯加氯", "C₂H₄ + Cl₂ -> C₂H₄Cl₂", "synthesis", "工业密闭过程", "乙烯与氯结合形成二氯乙烷，只用于认识组成关系。", "生成含氯有机物"),
  r("ethylene-bromine", "乙烯加溴", "C₂H₄ + Br₂ -> C₂H₄Br₂", "synthesis", "专业演示", "乙烯能让溴加到分子中，常用于帮助认识碳碳双键。", "溴的颜色逐渐变浅"),
  r("ethanol-oxidation-one", "乙醇氧化为乙醛", "2 C₂H₆O + O₂ -> 2 C₂H₄O + 2 H₂O", "redox", "生物或工业催化", "乙醇失去一部分氢并与氧作用，可以转变为乙醛和水。", "形成新的含氧分子"),
  r("ethanal-oxidation", "乙醛氧化为乙酸", "2 C₂H₄O + O₂ -> 2 C₂H₄O₂", "redox", "氧化过程", "乙醛继续获得氧可以形成乙酸，食醋发酵中有相关的多步变化。", "酸味逐渐形成"),
  r("esterification", "乙酸与乙醇形成乙酸乙酯", "C₂H₄O₂ + C₂H₆O -> C₄H₈O₂ + H₂O", "synthesis", "工业或专业条件", "乙酸与乙醇的原子重新组合，可形成有果香气味的乙酸乙酯和水。", "生成具有果香的物质"),
  r("methane-chlorination", "甲烷的一氯取代", "CH₄ + Cl₂ -> CH₃Cl + HCl", "replacement", "光照与专业密闭条件", "光照下甲烷中的一个氢可被氯取代，这是有机取代反应的简单示意。", "形成两种含氯物质"),
  r("methane-pyrolysis", "甲烷高温裂解", "2 CH₄ -> C₂H₂ + 3 H₂", "decomposition", "工业高温", "甲烷在高温过程中可以重新组合成乙炔和氢气。", "生成两种气体"),
  r("chlorine-water", "氯气与水", "Cl₂ + H₂O -> HCl + HClO", "redox", "水处理中的平衡", "氯进入水后可形成盐酸和次氯酸，次氯酸与消毒作用有关。", "形成具有氧化性的水溶液"),
  r("sulfur-dioxide-base", "二氧化硫与氢氧化钠", "SO₂ + 2 NaOH -> Na₂SO₃ + H₂O", "neutralization", "烟气处理", "碱液可以吸收酸性二氧化硫，生成亚硫酸钠和水。", "二氧化硫被吸收"),
  r("sodium-peroxide-water", "过氧化钠与水", "2 Na₂O₂ + 2 H₂O -> 4 NaOH + O₂", "redox", "仅作组成认识", "过氧化钠与水会生成氢氧化钠并释放氧气，反应放热且不可模仿。", "放热并产生氧气"),
  r("calcium-carbide-water", "碳化钙与水", "CaC₂ + 2 H₂O -> C₂H₂ + Ca(OH)₂", "exchange", "工业与专业操作", "碳化钙与水会产生乙炔和氢氧化钙，过程具有危险性，只作虚拟认识。", "产生可燃气体"),
];

export const CONSERVATION_REACTIONS = REACTION_DRAFTS.map(createReaction);
